# Generated by Django 5.0 on 2025-10-13 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bep", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mmiscaledefinition",
            name="color_hex",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hex color code from MMI-veileder 2.0 (e.g., '#BE2823' for MMI 100). Leave blank for custom levels.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="mmiscaledefinition",
            name="color_rgb",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RGB color from MMI-veileder 2.0 (e.g., '190,40,35' for MMI 100). Leave blank for custom levels.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mmiscaledefinition",
            name="name_en",
            field=models.CharField(
                blank=True,
                default="",
                help_text="English name from MMI-veileder (e.g., 'Foundation information', 'Concept information')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="mmiscaledefinition",
            name="mmi_level",
            field=models.IntegerField(
                help_text="MMI level (0-2000). Standard uses 0, 100, 125, 150...500, 600 with 25-point increments. Projects can add custom levels.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(2000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mmiscaledefinition",
            name="name",
            field=models.CharField(
                help_text="Norwegian name from MMI-veileder (e.g., 'Grunnlagsinformasjon', 'Konseptinformasjon')",
                max_length=100,
            ),
        ),
    ]
