# Generated by Django 6.0 on 2026-03-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0003_add_bep_template_and_project_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bepconfiguration',
            name='classification_system',
            field=models.CharField(choices=[('ns3451', 'NS 3451 (Bygningsdelstabell)'), ('omniclass', 'OmniClass'), ('uniclass', 'Uniclass 2015'), ('coclass', 'CoClass'), ('sfb', 'SfB'), ('custom', 'Custom')], default='ns3451', help_text='Primary classification system for type mapping', max_length=50),
        ),
    ]
