# Generated by Django 6.0 on 2026-01-25 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True, help_text='Only one config can be active per project')),
                ('name', models.CharField(blank=True, help_text='Optional name for this config version', max_length=100, null=True)),
                ('config', models.JSONField(default=dict, help_text='Full configuration as JSON')),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(help_text='Project this config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Config',
                'verbose_name_plural': 'Project Configs',
                'db_table': 'project_configs',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='project_con_project_79cc70_idx')],
            },
        ),
    ]
