# Generated by Django 6.0 on 2026-02-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfig',
            name='block_on_new_types',
            field=models.BooleanField(default=False, help_text='In controlled phase: block upload verification until new types reviewed'),
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='phase',
            field=models.CharField(choices=[('fluid', 'Fluid - New types auto-accepted'), ('controlled', 'Controlled - New types require review')], default='fluid', help_text='Project phase: fluid=auto-accept new types, controlled=require review', max_length=20),
        ),
    ]
