# Generated by Django 6.0 on 2026-02-14 22:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_sprint2_vault_immutable_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification_system', models.CharField(default='NS3451', help_text='Classification system (NS3451, OmniClass, etc.)', max_length=50)),
                ('classification_code', models.CharField(help_text="Classification code (e.g., '32', '22')", max_length=20)),
                ('discipline', models.CharField(choices=[('ARK', 'Architecture'), ('RIB', 'Structural'), ('RIBp', 'Structural Prefab'), ('RIG', 'Geotechnical'), ('RIV', 'HVAC'), ('RIVv', 'Ventilation'), ('RIVp', 'Plumbing'), ('RIVspr', 'Sprinkler'), ('RIkulde', 'Cooling'), ('RIvarme', 'Heating'), ('RIE', 'Electrical'), ('LARK', 'Landscape'), ('RIA', 'Acoustics'), ('RIBr', 'Fire Safety'), ('RIByfy', 'Building Physics'), ('RIM', 'Environmental'), ('BIM-K', 'BIM Coordinator'), ('BIM-M', 'BIM Manager'), ('PGL', 'Design Manager'), ('PM', 'Project Manager'), ('BH', 'Owner/Client')], help_text='BIM discipline code', max_length=20)),
                ('ownership_level', models.CharField(choices=[('primary', 'Primary - Must model'), ('secondary', 'Secondary - May model'), ('reference', 'Reference - Copy from others')], help_text='Level of ownership for this discipline', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional guidance for this assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this matrix entry belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_matrix', to='projects.project')),
            ],
            options={
                'db_table': 'responsibility_matrix',
                'ordering': ['classification_code', 'discipline'],
                'unique_together': {('project', 'classification_code', 'discipline')},
            },
        ),
    ]
