# Generated by Django 5.0 on 2025-10-13 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BEPConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, help_text="BEP version number"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Status of this BEP version",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="BIM Execution Plan",
                        help_text="BEP name or title",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of this BEP and its purpose"
                    ),
                ),
                (
                    "eir_document_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to EIR PDF/document (client requirements)",
                        null=True,
                    ),
                ),
                (
                    "bep_document_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to BEP PDF/document (delivery team plan)",
                        null=True,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("pofin", "POFIN (buildingSMART Norge)"),
                            ("iso19650", "ISO 19650 Generic"),
                            ("custom", "Custom"),
                        ],
                        default="pofin",
                        help_text="BIM framework this BEP follows",
                        max_length=50,
                    ),
                ),
                (
                    "cde_structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="CDE folder structure (WIP/Shared/Published/Archive)",
                    ),
                ),
                ("created_by", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this BEP applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beps",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "BEP Configuration",
                "verbose_name_plural": "BEP Configurations",
                "db_table": "bep_configurations",
                "ordering": ["-created_at"],
                "unique_together": {("project", "version")},
            },
        ),
        migrations.CreateModel(
            name="NamingConvention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("file_naming", "File Naming"),
                            ("element_naming", "Element Naming"),
                            ("layer_naming", "Layer Naming"),
                            ("classification", "Classification System"),
                            ("discipline_code", "Discipline Code"),
                        ],
                        help_text="Type of naming rule",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(help_text="Rule name", max_length=100)),
                ("description", models.TextField(help_text="What this rule enforces")),
                (
                    "pattern",
                    models.CharField(
                        help_text="Regex pattern or template string (e.g., '{project}_{discipline}_{type}_{number}.ifc')",
                        max_length=500,
                    ),
                ),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("regex", "Regular Expression"),
                            ("template", "Template String"),
                        ],
                        default="template",
                        help_text="Pattern type",
                        max_length=20,
                    ),
                ),
                (
                    "examples",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of example valid names: ['ARK-001_Building_A.ifc', 'RIV-002_Foundation.ifc']",
                    ),
                ),
                (
                    "applies_to_disciplines",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Empty = all disciplines. ['ARK', 'RIV'] = only those",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Must pass this check?"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        default="Name does not match project naming convention",
                        help_text="Error message to show when validation fails",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bep",
                    models.ForeignKey(
                        help_text="BEP this convention belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naming_conventions",
                        to="bep.bepconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Naming Convention",
                "verbose_name_plural": "Naming Conventions",
                "db_table": "naming_conventions",
                "ordering": ["bep", "category"],
            },
        ),
        migrations.CreateModel(
            name="RequiredPropertySet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ifc_type",
                    models.CharField(
                        help_text="IFC type (e.g., 'IfcWall', 'IfcDoor'). Use '*' for all types.",
                        max_length=50,
                    ),
                ),
                (
                    "mmi_level",
                    models.IntegerField(
                        help_text="Minimum MMI level where this Pset is required"
                    ),
                ),
                (
                    "pset_name",
                    models.CharField(
                        help_text="Property set name (e.g., 'Pset_WallCommon', 'Pset_DoorCommon')",
                        max_length=100,
                    ),
                ),
                (
                    "required_properties",
                    models.JSONField(
                        default=list,
                        help_text='\n        Array of required property definitions:\n        [\n            {\n                "name": "LoadBearing",\n                "type": "IfcBoolean",\n                "validation": {"required": true}\n            },\n            {\n                "name": "FireRating",\n                "type": "IfcLabel",\n                "validation": {"required": true, "pattern": "^(REI|EI)\\d+$"}\n            }\n        ]\n        ',
                    ),
                ),
                (
                    "optional_properties",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of property names that are optional but recommended",
                    ),
                ),
                (
                    "applies_to_disciplines",
                    models.JSONField(
                        blank=True, default=list, help_text="Empty = all disciplines"
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="error",
                        help_text="Severity if this Pset is missing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bep",
                    models.ForeignKey(
                        help_text="BEP this requirement belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_property_sets",
                        to="bep.bepconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Required Property Set",
                "verbose_name_plural": "Required Property Sets",
                "db_table": "required_property_sets",
                "ordering": ["bep", "ifc_type", "mmi_level"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., 'Preliminary Design', 'Detailed Design', 'For Construction'",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "target_mmi",
                    models.IntegerField(
                        help_text="Expected MMI level for this milestone"
                    ),
                ),
                (
                    "required_disciplines",
                    models.JSONField(
                        default=list,
                        help_text="List of disciplines that must deliver: ['ARK', 'RIV', 'ELEKT']",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(help_text="When should this be delivered?"),
                ),
                (
                    "submission_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Hard deadline (if different from target)",
                        null=True,
                    ),
                ),
                (
                    "review_checklist",
                    models.JSONField(
                        default=list,
                        help_text='\n        Review checklist items:\n        [\n            {"item": "Clash detection completed", "required": true},\n            {"item": "All GUIDs unique", "required": true},\n            {"item": "Property sets complete", "required": true},\n            {"item": "Naming conventions followed", "required": false}\n        ]\n        ',
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="upcoming",
                        help_text="Milestone status",
                        max_length=20,
                    ),
                ),
                (
                    "milestone_order",
                    models.IntegerField(default=0, help_text="Sort order"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bep",
                    models.ForeignKey(
                        help_text="BEP this milestone belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="bep.bepconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Milestone",
                "verbose_name_plural": "Submission Milestones",
                "db_table": "submission_milestones",
                "ordering": ["bep", "milestone_order", "target_date"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ifc_schema",
                    models.CharField(
                        choices=[
                            ("IFC2X3", "IFC 2x3"),
                            ("IFC4", "IFC 4.0"),
                            ("IFC4X3", "IFC 4.3"),
                        ],
                        default="IFC4",
                        help_text="Required IFC schema version",
                        max_length=20,
                    ),
                ),
                (
                    "model_view_definition",
                    models.CharField(
                        blank=True,
                        help_text="MVD name (e.g., 'CoordinationView 2.0', 'ReferenceView')",
                        max_length=100,
                    ),
                ),
                (
                    "coordinate_system_name",
                    models.CharField(
                        default="EPSG:25833",
                        help_text="EPSG code or coordinate system name",
                        max_length=100,
                    ),
                ),
                (
                    "coordinate_system_description",
                    models.TextField(
                        blank=True, help_text="Description of coordinate system"
                    ),
                ),
                (
                    "length_unit",
                    models.CharField(
                        choices=[("METRE", "Meter"), ("MILLIMETRE", "Millimeter")],
                        default="METRE",
                        help_text="Primary length unit",
                        max_length=20,
                    ),
                ),
                (
                    "area_unit",
                    models.CharField(
                        default="SQUARE_METRE", help_text="Area unit", max_length=20
                    ),
                ),
                (
                    "volume_unit",
                    models.CharField(
                        default="CUBIC_METRE", help_text="Volume unit", max_length=20
                    ),
                ),
                (
                    "geometry_tolerance",
                    models.FloatField(
                        default=0.001,
                        help_text="Geometric tolerance in length units (e.g., 0.001m = 1mm)",
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        default=500, help_text="Maximum IFC file size in MB"
                    ),
                ),
                (
                    "requirements_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional technical requirements (custom fields)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bep",
                    models.OneToOneField(
                        help_text="BEP this requirement belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_requirements",
                        to="bep.bepconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Requirement",
                "verbose_name_plural": "Technical Requirements",
                "db_table": "technical_requirements",
            },
        ),
        migrations.CreateModel(
            name="MMIScaleDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mmi_level",
                    models.IntegerField(
                        choices=[
                            (100, "MMI 100"),
                            (200, "MMI 200"),
                            (300, "MMI 300"),
                            (350, "MMI 350"),
                            (400, "MMI 400"),
                            (500, "MMI 500"),
                        ],
                        help_text="Norwegian MMI level (100-500)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="E.g., 'Concept Design', 'Coordination Design', 'Production Ready'",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="What this MMI level means for THIS project"
                    ),
                ),
                (
                    "geometry_requirements",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Example:\n        {\n            "detail_level": "symbolic|approximate|detailed|as_built",\n            "min_vertex_count": 8,\n            "requires_3d": true,\n            "collision_ready": false\n        }\n        ',
                    ),
                ),
                (
                    "information_requirements",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Example:\n        {\n            "requires_name": true,\n            "requires_description": false,\n            "requires_classification": true,\n            "requires_material": true,\n            "requires_system_membership": false,\n            "min_property_count": 5\n        }\n        ',
                    ),
                ),
                (
                    "discipline_specific_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='\n        Example:\n        {\n            "ARK": {"requires_loadbearing": true},\n            "RIV": {"requires_structural_analysis": true},\n            "ELEKT": {"requires_circuit_info": true}\n        }\n        ',
                    ),
                ),
                (
                    "applies_to_disciplines",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of discipline codes this MMI applies to ['ARK', 'RIV', 'ELEKT']",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, help_text="Sort order in UI"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bep",
                    models.ForeignKey(
                        help_text="BEP this MMI definition belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mmi_scale",
                        to="bep.bepconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "MMI Scale Definition",
                "verbose_name_plural": "MMI Scale Definitions",
                "db_table": "mmi_scale_definitions",
                "ordering": ["bep", "mmi_level"],
                "unique_together": {("bep", "mmi_level")},
            },
        ),
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_code",
                    models.CharField(
                        help_text="Unique code (e.g., 'GUID-001', 'GEOM-002')",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(help_text="Rule name", max_length=100)),
                ("description", models.TextField(help_text="What this rule checks")),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("guid", "GUID Validation"),
                            ("geometry", "Geometry Validation"),
                            ("property", "Property Validation"),
                            ("naming", "Naming Convention"),
                            ("classification", "Classification"),
                            ("relationship", "Relationship"),
                            ("clash", "Clash Detection"),
                            ("custom", "Custom Script"),
                        ],
                        help_text="Type of validation",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("error", "Error - Must fix"),
                            ("warning", "Warning - Should fix"),
                            ("info", "Info - Nice to have"),
                        ],
                        default="error",
                        help_text="Severity level",
                        max_length=20,
                    ),
                ),
                (
                    "rule_definition",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Rule logic definition. Structure depends on rule_type:\n\n        For \'guid\':\n        {\n            "check": "uniqueness",\n            "allow_duplicates": false\n        }\n\n        For \'geometry\':\n        {\n            "check": "has_3d_geometry",\n            "min_vertex_count": 8,\n            "applies_to_types": ["IfcWall", "IfcSlab"]\n        }\n\n        For \'property\':\n        {\n            "check": "has_property",\n            "pset_name": "Pset_WallCommon",\n            "property_name": "LoadBearing",\n            "applies_to_types": ["IfcWall"]\n        }\n\n        For \'custom\':\n        {\n            "script_id": "uuid-of-validation-script"\n        }\n        ',
                    ),
                ),
                (
                    "applies_to_ifc_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Empty = all types. ['IfcWall', 'IfcDoor'] = only those",
                    ),
                ),
                (
                    "applies_to_disciplines",
                    models.JSONField(
                        blank=True, default=list, help_text="Empty = all disciplines"
                    ),
                ),
                (
                    "min_mmi_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Only apply this rule at this MMI level or above",
                        null=True,
                    ),
                ),
                (
                    "error_message_template",
                    models.TextField(
                        default="Validation failed",
                        help_text="Error message template. Use {placeholders} for dynamic values.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Is this rule active?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bep",
                    models.ForeignKey(
                        help_text="BEP this rule belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_rules",
                        to="bep.bepconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Rule",
                "verbose_name_plural": "Validation Rules",
                "db_table": "validation_rules",
                "ordering": ["bep", "severity", "rule_code"],
                "unique_together": {("bep", "rule_code")},
            },
        ),
    ]
