# Generated by Django 6.0 on 2026-02-07 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bep', '0002_mmiscaledefinition_color_hex_and_more'),
        ('projects', '0003_sprint2_vault_immutable_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEPTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Template name (e.g., 'ISO 19650', 'POFIN Norway')", max_length=200)),
                ('framework', models.CharField(choices=[('pofin', 'POFIN (buildingSMART Norge)'), ('iso19650', 'ISO 19650 Generic'), ('custom', 'Custom')], default='pofin', help_text='BIM framework this template follows', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of this template and its intended use')),
                ('is_system', models.BooleanField(default=False, help_text='System templates are built-in and read-only')),
                ('default_disciplines', models.JSONField(blank=True, default=list, help_text='\n        Default discipline codes and names:\n        [\n            {"code": "ARK", "name": "Arkitekt"},\n            {"code": "RIB", "name": "Rådgivende Ingeniør Bygg"},\n            {"code": "RIV", "name": "Rådgivende Ingeniør VVS"},\n            {"code": "RIE", "name": "Rådgivende Ingeniør Elektro"}\n        ]\n        ')),
                ('default_coordinate_system', models.JSONField(blank=True, default=dict, help_text='\n        Default coordinate system settings:\n        {\n            "horizontal_crs_epsg": 25833,\n            "horizontal_crs_name": "ETRS89 / UTM zone 33N",\n            "vertical_crs": "NN2000"\n        }\n        ')),
                ('default_naming_conventions', models.JSONField(blank=True, default=list, help_text='Default naming convention patterns')),
                ('default_responsibility_matrix', models.JSONField(blank=True, default=dict, help_text='\n        Default NS3451 responsibility assignments:\n        {\n            "20": {"ARK": "primary"},\n            "22": {"RIB": "primary", "ARK": "secondary"},\n            "31": {"RIV": "primary"}\n        }\n        ')),
                ('default_mmi_requirements', models.JSONField(blank=True, default=dict, help_text='Default MMI level requirements per phase')),
                ('default_storeys', models.JSONField(blank=True, default=list, help_text='\n        Default storey structure (for templates with standard floor schemes):\n        [\n            {"name": "Plan U1", "code": "U1", "elevation": -3.0},\n            {"name": "Plan 01", "code": "01", "elevation": 0.0},\n            {"name": "Plan 02", "code": "02", "elevation": 3.5}\n        ]\n        ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'BEP Template',
                'verbose_name_plural': 'BEP Templates',
                'db_table': 'bep_templates',
                'ordering': ['is_system', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bepconfiguration',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional template to inherit defaults from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations', to='bep.beptemplate'),
        ),
        migrations.CreateModel(
            name='ProjectCoordinates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horizontal_crs_epsg', models.IntegerField(default=25833, help_text='EPSG code for horizontal CRS (e.g., 25833 for UTM33N)')),
                ('horizontal_crs_name', models.CharField(blank=True, default='ETRS89 / UTM zone 33N', help_text='Human-readable CRS name', max_length=100)),
                ('vertical_crs', models.CharField(default='NN2000', help_text="Vertical datum (e.g., 'NN2000', 'NN54')", max_length=50)),
                ('local_origin_x', models.DecimalField(decimal_places=3, default=0, help_text='Local origin X (typically 0)', max_digits=12)),
                ('local_origin_y', models.DecimalField(decimal_places=3, default=0, help_text='Local origin Y (typically 0)', max_digits=12)),
                ('local_origin_z', models.DecimalField(decimal_places=3, default=0, help_text='Local origin Z (typically 0)', max_digits=12)),
                ('eastings', models.DecimalField(blank=True, decimal_places=3, help_text='Eastings in CRS units (e.g., meters for UTM)', max_digits=15, null=True)),
                ('northings', models.DecimalField(blank=True, decimal_places=3, help_text='Northings in CRS units', max_digits=15, null=True)),
                ('orthometric_height', models.DecimalField(blank=True, decimal_places=3, help_text='Orthometric height above datum', max_digits=10, null=True)),
                ('true_north_rotation', models.DecimalField(decimal_places=4, default=0, help_text='True North rotation in degrees (positive = clockwise from grid north)', max_digits=8)),
                ('position_tolerance_m', models.DecimalField(decimal_places=3, default=0.1, help_text='Allowed deviation from expected position (meters)', max_digits=6)),
                ('rotation_tolerance_deg', models.DecimalField(decimal_places=3, default=0.1, help_text='Allowed deviation from expected rotation (degrees)', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(help_text='Project this coordinate config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Coordinates',
                'verbose_name_plural': 'Project Coordinates',
                'db_table': 'project_coordinates',
            },
        ),
        migrations.CreateModel(
            name='ProjectDiscipline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline_code', models.CharField(help_text='Standard code: ARK, RIB, RIV, RIE, LARK, RIG, etc.', max_length=10)),
                ('discipline_name', models.CharField(help_text="Full name (e.g., 'Arkitekt', 'Rådgivende Ingeniør Bygg')", max_length=100)),
                ('company_name', models.CharField(blank=True, help_text='Name of company responsible for this discipline', max_length=200)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact person', max_length=200)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('software', models.CharField(blank=True, help_text='Authoring software (Revit, Archicad, Tekla, etc.)', max_length=100)),
                ('source_code_mapping', models.CharField(blank=True, help_text="Maps internal codes (e.g., 'A') to standard ('ARK')", max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is this discipline currently active on the project?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this discipline belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Discipline',
                'verbose_name_plural': 'Project Disciplines',
                'db_table': 'project_disciplines',
                'ordering': ['project', 'discipline_code'],
                'unique_together': {('project', 'discipline_code')},
            },
        ),
        migrations.CreateModel(
            name='ProjectStorey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storey_name', models.CharField(help_text="Full storey name (e.g., 'Plan U1', 'Plan 01', 'Tak')", max_length=100)),
                ('storey_code', models.CharField(blank=True, help_text="Short code (e.g., 'U1', '01', 'T')", max_length=20)),
                ('elevation_m', models.DecimalField(decimal_places=3, help_text='Storey elevation in meters (relative to project zero)', max_digits=10)),
                ('tolerance_m', models.DecimalField(decimal_places=3, default=0.01, help_text='Allowed elevation deviation in meters', max_digits=6)),
                ('order', models.IntegerField(default=0, help_text='Sort order (lowest floor first, typically negative for basement)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this storey belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='storeys', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Storey',
                'verbose_name_plural': 'Project Storeys',
                'db_table': 'project_storeys',
                'ordering': ['project', 'order', 'elevation_m'],
                'unique_together': {('project', 'storey_name')},
            },
        ),
    ]
