# Generated by Django 5.0 on 2025-10-13 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("models", "0004_add_is_published_field"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "script_type",
                    models.CharField(
                        choices=[
                            ("python", "Python Script"),
                            ("validation_rule", "Validation Rule"),
                            ("export", "Export Script"),
                        ],
                        default="python",
                        max_length=50,
                    ),
                ),
                ("code", models.TextField(help_text="Python code to execute")),
                ("parameters_schema", models.JSONField(blank=True, default=dict)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("validation", "Validation"),
                            ("export", "Export"),
                            ("transform", "Transform"),
                            ("analysis", "Analysis"),
                            ("reporting", "Reporting"),
                        ],
                        default="analysis",
                        max_length=50,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True, help_text="Public scripts visible to all users"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        default="System", help_text="Script author", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scripts",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="scripts_categor_327bb3_idx"
                    ),
                    models.Index(
                        fields=["is_public"], name="scripts_is_publ_fa6993_idx"
                    ),
                    models.Index(
                        fields=["script_type"], name="scripts_script__8972ca_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AutomationWorkflow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("on_upload", "On Model Upload"),
                            ("scheduled", "Scheduled"),
                            ("manual", "Manual"),
                        ],
                        max_length=50,
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                ("default_parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, help_text="For scheduled workflows", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="projects.project",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflows",
                        to="scripting.script",
                    ),
                ),
            ],
            options={
                "db_table": "automation_workflows",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScriptExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("error", "Error"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Execution time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "output_log",
                    models.TextField(
                        blank=True, help_text="Captured stdout/stderr", null=True
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured results (counts, statistics)",
                    ),
                ),
                (
                    "result_files",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of file URLs in storage",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "executed_by_name",
                    models.CharField(blank=True, default="System", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="script_executions",
                        to="models.model",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="scripting.script",
                    ),
                ),
            ],
            options={
                "db_table": "script_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        help_text="upload, schedule, manual", max_length=50
                    ),
                ),
                (
                    "triggered_by_user_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_executions",
                        to="models.model",
                    ),
                ),
                (
                    "script_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_trigger",
                        to="scripting.scriptexecution",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="scripting.automationworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_executions",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="automationworkflow",
            index=models.Index(
                fields=["trigger_type"], name="automation__trigger_441303_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationworkflow",
            index=models.Index(
                fields=["is_active"], name="automation__is_acti_febdf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationworkflow",
            index=models.Index(
                fields=["project"], name="automation__project_10ec5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationworkflow",
            index=models.Index(
                fields=["next_run_at"], name="automation__next_ru_18034d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scriptexecution",
            index=models.Index(
                fields=["script"], name="script_exec_script__8576b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scriptexecution",
            index=models.Index(fields=["model"], name="script_exec_model_i_c9ebff_idx"),
        ),
        migrations.AddIndex(
            model_name="scriptexecution",
            index=models.Index(fields=["status"], name="script_exec_status_330eb0_idx"),
        ),
        migrations.AddIndex(
            model_name="scriptexecution",
            index=models.Index(
                fields=["-started_at"], name="script_exec_started_c714c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow"], name="workflow_ex_workflo_fc50f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(fields=["model"], name="workflow_ex_model_i_7d4704_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["-executed_at"], name="workflow_ex_execute_fded9a_idx"
            ),
        ),
    ]
