# Generated by Django 5.0 on 2025-10-13 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("models", "0004_add_is_published_field"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewerConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_viewers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewers",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viewer Configuration",
                "verbose_name_plural": "Viewer Configurations",
                "db_table": "viewer_configurations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ViewerGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("phase", "Construction Phase"),
                            ("discipline", "Discipline"),
                            ("zone", "Spatial Zone"),
                            ("custom", "Custom Group"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "is_expanded",
                    models.BooleanField(
                        default=True, help_text="Whether group is expanded in tree view"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="viewers.viewergroup",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="viewers.viewerconfiguration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viewer Group",
                "verbose_name_plural": "Viewer Groups",
                "db_table": "viewer_groups",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ViewerModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "offset_x",
                    models.FloatField(default=0.0, help_text="X offset in meters"),
                ),
                (
                    "offset_y",
                    models.FloatField(default=0.0, help_text="Y offset in meters"),
                ),
                (
                    "offset_z",
                    models.FloatField(default=0.0, help_text="Z offset in meters"),
                ),
                (
                    "rotation",
                    models.FloatField(
                        default=0.0, help_text="Rotation in degrees (Z-axis)"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "opacity",
                    models.FloatField(
                        default=1.0, help_text="0.0 (transparent) to 1.0 (opaque)"
                    ),
                ),
                (
                    "color_override",
                    models.CharField(
                        blank=True,
                        help_text="Hex color (e.g., #FF5733)",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="viewers.viewergroup",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewer_assignments",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viewer Model",
                "verbose_name_plural": "Viewer Models",
                "db_table": "viewer_models",
                "ordering": ["display_order"],
                "unique_together": {("group", "model")},
            },
        ),
    ]
