# Generated by Django 5.0 on 2025-10-13 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("viewers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="viewergroup",
            name="viewer",
        ),
        migrations.AddField(
            model_name="viewergroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_viewer_groups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="viewergroup",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description of this group"
            ),
        ),
        migrations.AddField(
            model_name="viewergroup",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewer_groups",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="viewergroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="ViewerConfiguration",
        ),
    ]
