# Generated by Django 5.0 on 2025-10-11 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("ifc_schema", models.CharField(blank=True, max_length=50, null=True)),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("error", "Error"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("version_number", models.IntegerField(default=1)),
                ("element_count", models.IntegerField(default=0)),
                ("storey_count", models.IntegerField(default=0)),
                ("system_count", models.IntegerField(default=0)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="models.model",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "models",
                "ordering": ["-created_at"],
                "unique_together": {("project", "version_number")},
            },
        ),
    ]
