# Generated by Django 5.0 on 2025-10-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="file_size",
            field=models.BigIntegerField(default=0, help_text="File size in bytes"),
        ),
    ]
