# Generated by Django 5.0 on 2025-10-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0004_add_is_published_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="celery_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async processing",
                max_length=255,
                null=True,
            ),
        ),
    ]
