# Generated by Django 5.0 on 2025-10-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0006_rename_celery_task_id_to_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="geometry_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("extracting", "Extracting"),
                    ("completed", "Completed"),
                    ("partial", "Partial"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Layer 2: Geometry extraction status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="parsing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("parsing", "Parsing"),
                    ("parsed", "Parsed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Layer 1: Metadata extraction status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="validation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("validating", "Validating"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Layer 3: Validation status",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Django Q task ID for async processing",
                max_length=255,
                null=True,
            ),
        ),
    ]
