# Generated by Django 5.0 on 2025-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0008_change_parent_model_cascade"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="fragments_generated_at",
            field=models.DateTimeField(
                blank=True, help_text="When Fragments file was generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="fragments_size_mb",
            field=models.FloatField(
                blank=True, help_text="Size of Fragments file in MB", null=True
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="fragments_url",
            field=models.URLField(
                blank=True,
                help_text="URL to ThatOpen Fragments file (optimized binary format)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="gis_basepoint_x",
            field=models.FloatField(
                blank=True,
                help_text="GIS X coordinate (Easting) - typically UTM or national grid",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="gis_basepoint_y",
            field=models.FloatField(
                blank=True,
                help_text="GIS Y coordinate (Northing) - typically UTM or national grid",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="gis_basepoint_z",
            field=models.FloatField(
                blank=True,
                help_text="GIS Z coordinate (elevation above sea level) in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="gis_crs",
            field=models.CharField(
                blank=True,
                help_text="Coordinate Reference System (e.g., 'EPSG:25832' for UTM Zone 32N)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="local_basepoint_x",
            field=models.FloatField(
                default=0,
                help_text="Local X coordinate - typically 0 at project basepoint",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="local_basepoint_y",
            field=models.FloatField(
                default=0,
                help_text="Local Y coordinate - typically 0 at project basepoint",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="local_basepoint_z",
            field=models.FloatField(
                default=0,
                help_text="Local Z coordinate - typically 0 at project basepoint",
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="transformation_matrix",
            field=models.JSONField(
                blank=True,
                help_text="4x4 transformation matrix for GIS to Local coordinate conversion",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="model",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async processing",
                max_length=255,
                null=True,
            ),
        ),
    ]
