# Generated by Django 5.0 on 2025-12-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "models",
            "0009_model_fragments_generated_at_model_fragments_size_mb_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="ifc_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Creation/modification date from IFC file (IfcOwnerHistory)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="version_diff",
            field=models.JSONField(
                blank=True,
                help_text="Diff summary: {entities: {created: N, updated: N, removed: N}}",
                null=True,
            ),
        ),
    ]
