# Generated by Django 5.0 on 2025-12-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0010_add_version_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="fork_description",
            field=models.TextField(
                blank=True,
                help_text="Description of what this fork explores/changes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="fork_name",
            field=models.CharField(
                blank=True,
                help_text="Human-readable fork name (e.g., 'LCA Timber Alternative')",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="fork_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("analysis", "Analysis"),
                    ("lca_scenario", "LCA Scenario"),
                    ("design_option", "Design Option"),
                    ("client_review", "Client Review"),
                    ("archive", "Archive Snapshot"),
                ],
                help_text="Purpose of this fork",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="forked_at",
            field=models.DateTimeField(
                blank=True, help_text="When this fork was created", null=True
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                help_text="Source model this was forked from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="models.model",
            ),
        ),
    ]
