# Generated by Django 5.0 on 2025-12-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0011_add_fork_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="material_count",
            field=models.IntegerField(
                default=0, help_text="Number of unique materials"
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="type_count",
            field=models.IntegerField(
                default=0, help_text="Number of IFC type definitions"
            ),
        ),
        migrations.AddField(
            model_name="model",
            name="type_summary",
            field=models.JSONField(
                blank=True,
                help_text="Type breakdown: [{ifc_type: 'IfcWall', count: 150}, ...]",
                null=True,
            ),
        ),
    ]
