# Generated by Django 6.0 on 2026-02-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_add_fragments_status'),
        ('projects', '0003_sprint2_vault_immutable_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='discipline',
            field=models.CharField(blank=True, choices=[('ARK', 'Architecture'), ('RIB', 'Structural'), ('RIV', 'Mechanical/HVAC'), ('RIE', 'Electrical'), ('LARK', 'Landscape'), ('RIG', 'Geotechnical')], help_text='Model discipline - auto-inferred from filename, can be overridden', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='is_primary_for_discipline',
            field=models.BooleanField(default=False, help_text='This is THE authoritative model for this discipline (e.g., main ARK model = room source of truth)'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['discipline'], name='models_discipl_21983f_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['project', 'discipline'], name='models_project_dc87cb_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['is_primary_for_discipline'], name='models_is_prim_1cdd11_idx'),
        ),
    ]
