# Generated by Django 6.0 on 2026-02-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_sprint1_gatekeeper_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='discipline',
            field=models.CharField(blank=True, choices=[('ARK', 'Architecture'), ('RIB', 'Structural'), ('RIBp', 'Structural Prefab'), ('RIG', 'Geotechnical'), ('RIV', 'HVAC'), ('RIVv', 'Ventilation'), ('RIVp', 'Plumbing'), ('RIVspr', 'Sprinkler'), ('RIkulde', 'Cooling'), ('RIvarme', 'Heating'), ('RIE', 'Electrical'), ('LARK', 'Landscape')], help_text='Model discipline - auto-inferred from filename, can be overridden', max_length=20, null=True),
        ),
    ]
