# Generated by Django 5.0 on 2026-04-28 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0017_model_checksum_sha256"),
        ("projects", "0004_responsibilitymatrix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                ("file_size", models.BigIntegerField(default=0, help_text="Bytes")),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("ifc", "IFC"),
                            ("las", "LAS Point Cloud"),
                            ("laz", "LAZ Point Cloud"),
                            ("e57", "E57 Point Cloud"),
                            ("dwg", "AutoCAD DWG"),
                            ("dxf", "AutoCAD DXF"),
                            ("pdf", "PDF"),
                            ("docx", "Word"),
                            ("xlsx", "Excel"),
                            ("pptx", "PowerPoint"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("xml", "XML"),
                            ("svg", "SVG"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("version_number", models.IntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="models.sourcefile",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_source_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "source_files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "discovered_crs",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "crs_source",
                    models.CharField(
                        blank=True,
                        help_text="Where the CRS came from (IfcMapConversion | filename | manual)",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("crs_confidence", models.FloatField(blank=True, null=True)),
                (
                    "discovered_units",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"length": "mm", "area": "m2", "angle": "deg"}',
                    ),
                ),
                (
                    "quality_report",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"total_elements": N, "typed": N, "untyped": N, "dropped": [...]}',
                    ),
                ),
                (
                    "log_entries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {ts, level, stage, message, details} entries",
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("extractor_version", models.CharField(blank=True, max_length=100)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction_runs",
                        to="models.sourcefile",
                    ),
                ),
            ],
            options={
                "db_table": "extraction_runs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="model",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_models",
                to="models.sourcefile",
            ),
        ),
        migrations.AddIndex(
            model_name="sourcefile",
            index=models.Index(
                fields=["project", "is_current"], name="source_file_project_6c6a05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractionrun",
            index=models.Index(
                fields=["source_file", "-started_at"],
                name="extraction__source__633271_idx",
            ),
        ),
    ]
