# Generated by Django 5.0 on 2026-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_add_fragments_format_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='URL to PNG thumbnail image generated from the IFC model', max_length=500, null=True),
        ),
    ]
