/**
 * Public surface for dashboard primitives.
 *
 * What lives here vs. components/ui/:
 *   - components/ui/         shadcn-canonical primitives (Radix-shaped,
 *                            generated by the shadcn CLI). Generic.
 *   - dashboard-primitives/  Domain primitives for dashboard tile
 *                            composition. Compose ui/ primitives, add
 *                            sprucelab-specific tokens (discipline
 *                            colors, traffic-light tints, coverage bars).
 *
 * See README.md in this directory for the full contract.
 */

export { MetricCard } from './MetricCard';
export type { MetricCardProps } from './MetricCard';
