# Generated by Django 6.0 on 2026-04-02 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_responsibilitymatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('rør', 'Rør'), ('tetthet', 'Tetthet'), ('brann', 'Brann'), ('elektro', 'Elektro'), ('betong', 'Betong'), ('stål', 'Stål'), ('tre', 'Tre'), ('ventilasjon', 'Ventilasjon'), ('generell', 'Generell')], default='generell', max_length=50)),
                ('regulation_ref', models.CharField(blank=True, help_text="E.g. 'TEK17 kap. 15, NS 3055'", max_length=255, null=True)),
                ('is_system_template', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Null for system templates shared across all projects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='projects.project')),
            ],
            options={
                'db_table': 'field_checklist_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, help_text="E.g. '2. etasje, bad hovedsoverom'", max_length=255, null=True)),
                ('status', models.CharField(choices=[('draft', 'Utkast'), ('in_progress', 'Pågår'), ('completed', 'Fullført'), ('signed', 'Signert')], default='draft', max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='projects.project')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='field.checklisttemplate')),
            ],
            options={
                'db_table': 'field_checklists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_type', models.CharField(choices=[('drawing', 'Tegning'), ('tek17', 'TEK17'), ('product_manual', 'Produktblad'), ('design_spec', 'Prosjektbeskrivelse'), ('ns_standard', 'NS Standard'), ('custom', 'Annet'), ('none', 'Ingen')], default='none', max_length=20)),
                ('reference_code', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_description', models.TextField(blank=True, null=True)),
                ('reference_document_url', models.URLField(blank=True, null=True)),
                ('reference_page', models.CharField(blank=True, max_length=50, null=True)),
                ('acceptance_criteria', models.TextField(blank=True, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('tolerance_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tolerance_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('requires_measurement', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='field.checklisttemplate')),
            ],
            options={
                'db_table': 'field_checklist_template_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('reference_type', models.CharField(blank=True, choices=[('drawing', 'Tegning'), ('tek17', 'TEK17'), ('product_manual', 'Produktblad'), ('design_spec', 'Prosjektbeskrivelse'), ('ns_standard', 'NS Standard'), ('custom', 'Annet'), ('none', 'Ingen')], max_length=20, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_description', models.TextField(blank=True, null=True)),
                ('reference_document_url', models.URLField(blank=True, null=True)),
                ('reference_page', models.CharField(blank=True, max_length=50, null=True)),
                ('acceptance_criteria', models.TextField(blank=True, null=True)),
                ('measurement_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('tolerance_min', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('tolerance_max', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('requires_photo', models.BooleanField(default=False)),
                ('is_critical', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Venter'), ('ok', 'OK'), ('deviation', 'Avvik'), ('not_applicable', 'Ikke aktuelt')], default='pending', max_length=20)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checked_by', models.CharField(blank=True, max_length=255, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('deviation_description', models.TextField(blank=True, null=True)),
                ('deviation_responsible', models.CharField(blank=True, choices=[('prosjekterende', 'Prosjekterende'), ('utførende', 'Utførende'), ('annet', 'Annet')], max_length=20, null=True)),
                ('deviation_action', models.CharField(blank=True, choices=[('stopp', 'Stopp arbeidet'), ('fortsett_med_forbehold', 'Fortsett med forbehold'), ('foreslå_løsning', 'Foreslå løsning')], max_length=30, null=True)),
                ('deviation_resolved', models.BooleanField(default=False)),
                ('deviation_resolved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('deviation_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='field.checklist')),
                ('template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='field.checklisttemplateitem')),
            ],
            options={
                'db_table': 'field_check_items',
                'ordering': ['sort_order'],
            },
        ),
    ]
