# Generated by Django 6.0 on 2026-05-05 18:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0007_projectconfig_block_on_storey_deviation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Operator-facing label', max_length=255)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prefix', models.CharField(help_text='First 8 chars of the raw token, used by `spruce embed pass list`', max_length=8)),
                ('allowed_origins', models.JSONField(default=list, help_text='Exact-match parent origins, e.g. ["https://skiplum-pages.example"]')),
                ('capabilities', models.JSONField(default=list, help_text='Capability strings; v1 set: read:instances, read:capabilities, read:dashboards')),
                ('ttl_seconds', models.PositiveIntegerField(default=3600)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embed_tokens_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embed_tokens', to='projects.project')),
            ],
            options={
                'db_table': 'embed_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'revoked_at'], name='embed_token_project_38a9af_idx'), models.Index(fields=['expires_at'], name='embed_token_expires_03af44_idx')],
            },
        ),
    ]
