# Generated by Django 5.0 on 2026-04-28 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0004_responsibilitymatrix"),
    ]

    operations = [
        migrations.CreateModel(
            name="CDEConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cde_type",
                    models.CharField(
                        choices=[
                            ("dalux", "Dalux"),
                            ("bim360", "BIM360/ACC"),
                            ("trimble_connect", "Trimble Connect"),
                            ("sharepoint", "SharePoint"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("config", models.JSONField(default=dict)),
                ("vault_secret_id", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cde_connections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "automation_cde_connections",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("single_project", "Single Project"),
                            ("multi_project", "Multi-Project"),
                        ],
                        default="single_project",
                        max_length=20,
                    ),
                ),
                ("parameters_schema", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_template",
                    models.BooleanField(
                        default=False,
                        help_text="Global template available to all projects",
                    ),
                ),
                ("author_name", models.CharField(default="System", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "automation_pipelines",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="automation__is_acti_ae9410_idx"
                    ),
                    models.Index(fields=["scope"], name="automation__scope_2c1ca8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("scheduled", "Scheduled"),
                            ("cde_webhook", "CDE Webhook"),
                            ("cli", "CLI Triggered"),
                            ("daemon", "Daemon Poll"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("agent_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "agent_hostname",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("triggered_by", models.CharField(blank=True, max_length=255)),
                ("steps_total", models.PositiveIntegerField(default=0)),
                ("steps_completed", models.PositiveIntegerField(default=0)),
                ("steps_failed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="automation.pipeline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_runs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "automation_pipeline_runs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("cde_sync", "CDE Sync"),
                            ("script", "Script Execution"),
                            ("file_transform", "File Transform"),
                            ("distribution", "Distribution"),
                            ("webhook", "Webhook"),
                            ("condition", "Condition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("config", models.JSONField(default=dict)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("retry_delay_seconds", models.PositiveIntegerField(default=60)),
                ("continue_on_failure", models.BooleanField(default=False)),
                ("timeout_seconds", models.PositiveIntegerField(default=3600)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="automation.pipeline",
                    ),
                ),
            ],
            options={
                "db_table": "automation_pipeline_steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PipelineStepRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("output_log", models.TextField(blank=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("output_files", models.JSONField(blank=True, default=list)),
                (
                    "pipeline_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_runs",
                        to="automation.pipelinerun",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="automation.pipelinestep",
                    ),
                ),
            ],
            options={
                "db_table": "automation_pipeline_step_runs",
                "ordering": ["step__order"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPipelineConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parameters_override", models.JSONField(blank=True, default=dict)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cde_connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="automation.cdeconnection",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_configs",
                        to="automation.pipeline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_configs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "automation_project_pipeline_configs",
            },
        ),
        migrations.CreateModel(
            name="AgentRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("hostname", models.CharField(max_length=255)),
                ("api_key_hash", models.CharField(max_length=64)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="automation_agents",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "automation_agents",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="automation__is_acti_01bf55_idx"
                    ),
                    models.Index(
                        fields=["last_seen_at"], name="automation__last_se_b0808f_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cdeconnection",
            index=models.Index(
                fields=["project"], name="automation__project_bb6945_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cdeconnection",
            index=models.Index(
                fields=["cde_type"], name="automation__cde_typ_2967aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cdeconnection",
            index=models.Index(
                fields=["is_active"], name="automation__is_acti_023e13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["pipeline"], name="automation__pipelin_2aeb23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["project"], name="automation__project_7c5e82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(fields=["status"], name="automation__status_b67f8a_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["-created_at"], name="automation__created_d64fc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinerun",
            index=models.Index(
                fields=["agent_id"], name="automation__agent_i_5c95b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestep",
            index=models.Index(
                fields=["pipeline", "order"], name="automation__pipelin_735073_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinestep",
            index=models.Index(
                fields=["step_type"], name="automation__step_ty_32bd28_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pipelinestep",
            unique_together={("pipeline", "order")},
        ),
        migrations.AddIndex(
            model_name="pipelinesteprun",
            index=models.Index(
                fields=["pipeline_run"], name="automation__pipelin_f4cf52_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pipelinesteprun",
            index=models.Index(fields=["step"], name="automation__step_id_b5bade_idx"),
        ),
        migrations.AddIndex(
            model_name="pipelinesteprun",
            index=models.Index(fields=["status"], name="automation__status_3cd489_idx"),
        ),
        migrations.AddIndex(
            model_name="projectpipelineconfig",
            index=models.Index(
                fields=["project"], name="automation__project_c4a7e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectpipelineconfig",
            index=models.Index(
                fields=["pipeline"], name="automation__pipelin_aee0cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectpipelineconfig",
            index=models.Index(
                fields=["is_enabled"], name="automation__is_enab_5777d8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectpipelineconfig",
            unique_together={("project", "pipeline")},
        ),
    ]
