# Generated by Django 5.0 on 2026-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0002_webhooksubscription_webhookdelivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentregistration",
            name="scope",
            field=models.CharField(
                choices=[
                    ("read_only", "Read only (GET only)"),
                    ("operator", "Operator (read + write data resources)"),
                    ("admin", "Admin (read + write + manage users/agents)"),
                ],
                default="operator",
                help_text="What this agent token may do across the REST surface.",
                max_length=16,
            ),
        ),
    ]
