# Generated by Django 5.0 on 2025-10-11 19:43

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IFCEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ifc_guid", models.CharField(max_length=22)),
                ("ifc_type", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("storey_id", models.UUIDField(blank=True, null=True)),
                ("has_geometry", models.BooleanField(default=False)),
                ("vertex_count", models.IntegerField(default=0)),
                ("triangle_count", models.IntegerField(default=0)),
                ("bbox_min_x", models.FloatField(blank=True, null=True)),
                ("bbox_min_y", models.FloatField(blank=True, null=True)),
                ("bbox_min_z", models.FloatField(blank=True, null=True)),
                ("bbox_max_x", models.FloatField(blank=True, null=True)),
                ("bbox_max_y", models.FloatField(blank=True, null=True)),
                ("bbox_max_z", models.FloatField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "db_table": "ifc_entities",
            },
        ),
        migrations.CreateModel(
            name="Geometry",
            fields=[
                (
                    "entity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="geometry",
                        serialize=False,
                        to="entities.ifcentity",
                    ),
                ),
                ("vertices_original", models.BinaryField(blank=True, null=True)),
                ("faces_original", models.BinaryField(blank=True, null=True)),
                ("vertices_simplified", models.BinaryField(blank=True, null=True)),
                ("faces_simplified", models.BinaryField(blank=True, null=True)),
                ("simplification_ratio", models.FloatField(blank=True, null=True)),
                (
                    "geometry_file_path",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "db_table": "geometry",
            },
        ),
        migrations.CreateModel(
            name="GraphEdge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relationship_type", models.CharField(max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_edges",
                        to="models.model",
                    ),
                ),
                (
                    "source_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="entities.ifcentity",
                    ),
                ),
                (
                    "target_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="entities.ifcentity",
                    ),
                ),
            ],
            options={
                "db_table": "graph_edges",
            },
        ),
        migrations.CreateModel(
            name="IFCType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type_guid", models.CharField(max_length=22)),
                ("type_name", models.CharField(blank=True, max_length=255, null=True)),
                ("ifc_type", models.CharField(max_length=100)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "db_table": "ifc_types",
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "material_guid",
                    models.CharField(blank=True, max_length=22, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("properties", models.JSONField(blank=True, default=dict)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "db_table": "materials",
            },
        ),
        migrations.CreateModel(
            name="MaterialAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer_thickness", models.FloatField(blank=True, null=True)),
                ("layer_order", models.IntegerField(default=1)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_assignments",
                        to="entities.ifcentity",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="entities.material",
                    ),
                ),
            ],
            options={
                "db_table": "material_assignments",
            },
        ),
        migrations.CreateModel(
            name="PropertySet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pset_name", models.CharField(max_length=255)),
                ("property_name", models.CharField(max_length=255)),
                ("property_value", models.TextField(blank=True, null=True)),
                (
                    "property_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_sets",
                        to="entities.ifcentity",
                    ),
                ),
            ],
            options={
                "db_table": "property_sets",
            },
        ),
        migrations.CreateModel(
            name="SpatialHierarchy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hierarchy_level",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("site", "Site"),
                            ("building", "Building"),
                            ("storey", "Storey"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "path",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=22),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spatial_parents",
                        to="entities.ifcentity",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spatial_hierarchy",
                        to="models.model",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spatial_children",
                        to="entities.ifcentity",
                    ),
                ),
            ],
            options={
                "db_table": "spatial_hierarchy",
            },
        ),
        migrations.CreateModel(
            name="StorageMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                ("spatial_structure_bytes", models.BigIntegerField(default=0)),
                ("elements_metadata_bytes", models.BigIntegerField(default=0)),
                ("properties_bytes", models.BigIntegerField(default=0)),
                ("systems_bytes", models.BigIntegerField(default=0)),
                ("materials_bytes", models.BigIntegerField(default=0)),
                ("relationships_bytes", models.BigIntegerField(default=0)),
                ("geometry_original_bytes", models.BigIntegerField(default=0)),
                ("geometry_simplified_bytes", models.BigIntegerField(default=0)),
                ("total_bytes", models.BigIntegerField(default=0)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_metrics",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "db_table": "storage_metrics",
            },
        ),
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("system_guid", models.CharField(max_length=22)),
                (
                    "system_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "system_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="systems",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "db_table": "systems",
            },
        ),
        migrations.CreateModel(
            name="SystemMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="system_memberships",
                        to="entities.ifcentity",
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="entities.system",
                    ),
                ),
            ],
            options={
                "db_table": "system_memberships",
            },
        ),
        migrations.CreateModel(
            name="TypeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_assignments",
                        to="entities.ifcentity",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="entities.ifctype",
                    ),
                ),
            ],
            options={
                "db_table": "type_assignments",
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ifc_guid", models.CharField(max_length=22)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("added", "Added"),
                            ("removed", "Removed"),
                            ("modified", "Modified"),
                            ("geometry_changed", "Geometry Changed"),
                            ("property_changed", "Property Changed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_details", models.JSONField(blank=True, default=dict)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="models.model",
                    ),
                ),
                (
                    "previous_model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_changes",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "db_table": "change_log",
                "indexes": [
                    models.Index(
                        fields=["change_type"], name="change_log_change__332487_idx"
                    ),
                    models.Index(
                        fields=["ifc_guid"], name="change_log_ifc_gui_9d98d3_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["ifc_type"], name="ifc_entitie_ifc_typ_eca66f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["ifc_guid"], name="ifc_entitie_ifc_gui_9ef35a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["storey_id"], name="ifc_entitie_storey__2d6466_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ifcentity",
            unique_together={("model", "ifc_guid")},
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(
                fields=["source_entity"], name="graph_edges_source__84883a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(
                fields=["target_entity"], name="graph_edges_target__8badfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="graphedge",
            index=models.Index(
                fields=["relationship_type"], name="graph_edges_relatio_1cf179_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ifctype",
            unique_together={("model", "type_guid")},
        ),
        migrations.AlterUniqueTogether(
            name="material",
            unique_together={("model", "material_guid")},
        ),
        migrations.AlterUniqueTogether(
            name="materialassignment",
            unique_together={("entity", "material", "layer_order")},
        ),
        migrations.AddIndex(
            model_name="propertyset",
            index=models.Index(
                fields=["pset_name"], name="property_se_pset_na_204da7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="propertyset",
            index=models.Index(
                fields=["property_name"], name="property_se_propert_6e3343_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="spatialhierarchy",
            index=models.Index(
                fields=["hierarchy_level"], name="spatial_hie_hierarc_7ecb91_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="system",
            unique_together={("model", "system_guid")},
        ),
        migrations.AlterUniqueTogether(
            name="systemmembership",
            unique_together={("system", "entity")},
        ),
        migrations.AlterUniqueTogether(
            name="typeassignment",
            unique_together={("entity", "type")},
        ),
    ]
