# Generated by Django 5.0 on 2025-10-12 12:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0001_initial"),
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IFCValidationReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("warning", "Warning"),
                            ("fail", "Fail"),
                        ],
                        default="pass",
                        max_length=20,
                    ),
                ),
                ("schema_valid", models.BooleanField(default=True)),
                ("total_elements", models.IntegerField(default=0)),
                ("elements_with_issues", models.IntegerField(default=0)),
                ("schema_errors", models.JSONField(blank=True, default=list)),
                ("schema_warnings", models.JSONField(blank=True, default=list)),
                ("guid_issues", models.JSONField(blank=True, default=list)),
                ("geometry_issues", models.JSONField(blank=True, default=list)),
                ("property_issues", models.JSONField(blank=True, default=list)),
                ("lod_issues", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_reports",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "db_table": "ifc_validation_reports",
                "ordering": ["-validated_at"],
                "indexes": [
                    models.Index(
                        fields=["overall_status"], name="ifc_validat_overall_4151a4_idx"
                    ),
                    models.Index(
                        fields=["validated_at"], name="ifc_validat_validat_1a2e07_idx"
                    ),
                ],
            },
        ),
    ]
