# Generated by Django 5.0 on 2025-10-20 19:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0002_add_ifc_validation_report"),
        ("models", "0004_add_is_published_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        default="failed",
                        max_length=20,
                    ),
                ),
                ("ifc_schema", models.CharField(blank=True, max_length=50, null=True)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("stage_results", models.JSONField(blank=True, default=list)),
                ("total_entities_processed", models.IntegerField(default=0)),
                ("total_entities_skipped", models.IntegerField(default=0)),
                ("total_entities_failed", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("catastrophic_failure", models.BooleanField(default=False)),
                (
                    "failure_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("file_open", "File Open"),
                            ("validation", "Validation"),
                            ("spatial_hierarchy", "Spatial Hierarchy"),
                            ("materials", "Materials"),
                            ("types", "Types"),
                            ("systems", "Systems"),
                            ("elements", "Elements"),
                            ("properties", "Property Sets"),
                            ("graph_edges", "Graph Edges"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("failure_exception", models.TextField(blank=True, null=True)),
                ("failure_traceback", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_reports",
                        to="models.model",
                    ),
                ),
            ],
            options={
                "db_table": "processing_reports",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["overall_status"], name="processing__overall_9d8296_idx"
                    ),
                    models.Index(
                        fields=["started_at"], name="processing__started_b2d3bf_idx"
                    ),
                ],
            },
        ),
    ]
