# Generated by Django 5.0 on 2025-10-20 19:54

from django.db import migrations, models


def clean_null_material_guids(apps, schema_editor):
    """
    Remove any materials with NULL material_guid before applying NOT NULL constraint.

    This is safe because:
    1. IfcMaterial doesn't have GlobalId (not an IfcRoot entity)
    2. Old materials were incorrectly stored with NULL guid
    3. New extraction code will properly populate material_guid with step ID
    """
    Material = apps.get_model('entities', 'Material')
    deleted_count = Material.objects.filter(material_guid__isnull=True).delete()[0]

    if deleted_count > 0:
        print(f"  Deleted {deleted_count} Material records with NULL material_guid")


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0003_processingreport"),
    ]

    # Use atomic=False to avoid "pending trigger events" error in PostgreSQL
    # This allows the delete operation to commit before the ALTER TABLE
    atomic = False

    operations = [
        # Step 1: Clean up NULL values
        migrations.RunPython(
            clean_null_material_guids,
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 2: Apply NOT NULL constraint
        migrations.AlterField(
            model_name="material",
            name="material_guid",
            field=models.CharField(max_length=50),
        ),
    ]
