# Generated by Django 5.0 on 2025-10-24 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0004_material_guid_step_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="geometry",
            name="bbox_max_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geometry",
            name="bbox_max_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geometry",
            name="bbox_max_z",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geometry",
            name="bbox_min_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geometry",
            name="bbox_min_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geometry",
            name="bbox_min_z",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="geometry",
            name="extracted_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="When geometry was extracted",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="geometry",
            name="triangle_count",
            field=models.IntegerField(
                default=0, help_text="Number of triangles in original mesh"
            ),
        ),
        migrations.AddField(
            model_name="geometry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="geometry",
            name="vertex_count",
            field=models.IntegerField(
                default=0, help_text="Number of vertices in original mesh"
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="geometry_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("no_representation", "No Representation"),
                ],
                default="pending",
                help_text="Status of geometry extraction for this element",
                max_length=20,
            ),
        ),
    ]
