# Generated by Django 5.0 on 2025-11-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0005_add_layered_status_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ifcentity",
            name="bbox_max_x",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="bbox_max_y",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="bbox_max_z",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="bbox_min_x",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="bbox_min_y",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="bbox_min_z",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="geometry_status",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="has_geometry",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="triangle_count",
        ),
        migrations.RemoveField(
            model_name="ifcentity",
            name="vertex_count",
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="area",
            field=models.FloatField(
                blank=True,
                help_text="Net area in square meters (m²) - from Qto_*BaseQuantities",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="height",
            field=models.FloatField(
                blank=True,
                help_text="Height in meters (m) - for vertical elements",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="length",
            field=models.FloatField(
                blank=True,
                help_text="Length in meters (m) - for linear elements",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="perimeter",
            field=models.FloatField(
                blank=True,
                help_text="Perimeter in meters (m) - for boundary calculations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="volume",
            field=models.FloatField(
                blank=True,
                help_text="Net volume in cubic meters (m³) - from Qto_*BaseQuantities",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ifcentity",
            name="ifc_guid",
            field=models.CharField(
                help_text="IFC GlobalId - unique identifier", max_length=22
            ),
        ),
        migrations.AlterField(
            model_name="ifcentity",
            name="ifc_type",
            field=models.CharField(
                help_text="IFC class (IfcWall, IfcDoor, etc.)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="ifcentity",
            name="storey_id",
            field=models.UUIDField(
                blank=True, help_text="Reference to parent storey", null=True
            ),
        ),
        migrations.DeleteModel(
            name="Geometry",
        ),
    ]
