# Generated by Django 5.0 on 2025-12-12 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0006_remove_ifcentity_bbox_max_x_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "epd_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="EPD/LCA data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "product_library",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="MaterialMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "standard_name",
                    models.CharField(
                        blank=True,
                        help_text="Normalized material name",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "density_kg_m3",
                    models.FloatField(
                        blank=True, help_text="Material density in kg/m³", null=True
                    ),
                ),
                (
                    "epd_reference",
                    models.CharField(
                        blank=True,
                        help_text="EPD database reference",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "thermal_conductivity",
                    models.FloatField(blank=True, help_text="W/(m·K)", null=True),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("mapped", "Mapped"),
                            ("ignored", "Ignored"),
                            ("review", "Needs Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("mapped_by", models.CharField(blank=True, max_length=255, null=True)),
                ("mapped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping",
                        to="entities.material",
                    ),
                ),
            ],
            options={
                "db_table": "material_mappings",
                "indexes": [
                    models.Index(
                        fields=["mapping_status"], name="material_ma_mapping_b03ec9_idx"
                    ),
                    models.Index(
                        fields=["standard_name"], name="material_ma_standar_d68b6c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TypeLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "layer_order",
                    models.IntegerField(
                        help_text="Layer position (1 = exterior/bottom)"
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        blank=True,
                        help_text="Material name (if material not in DB)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "thickness_mm",
                    models.FloatField(help_text="Layer thickness in millimeters"),
                ),
                ("is_structural", models.BooleanField(default=False)),
                ("is_ventilated", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ifc_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="entities.ifctype",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="type_layers",
                        to="entities.material",
                    ),
                ),
            ],
            options={
                "db_table": "type_layers",
                "ordering": ["ifc_type", "layer_order"],
                "unique_together": {("ifc_type", "layer_order")},
            },
        ),
        migrations.CreateModel(
            name="TypeMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ns3451_code",
                    models.CharField(
                        blank=True,
                        help_text="NS-3451 building part code (e.g., '32.21')",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mapping_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("mapped", "Mapped"),
                            ("ignored", "Ignored"),
                            ("review", "Needs Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        blank=True,
                        help_text="Mapping confidence (auto/manual/high/low)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("mapped_by", models.CharField(blank=True, max_length=255, null=True)),
                ("mapped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ifc_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping",
                        to="entities.ifctype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="type_mappings",
                        to="entities.productlibrary",
                    ),
                ),
            ],
            options={
                "db_table": "type_mappings",
                "indexes": [
                    models.Index(
                        fields=["mapping_status"], name="type_mappin_mapping_0d7d8a_idx"
                    ),
                    models.Index(
                        fields=["ns3451_code"], name="type_mappin_ns3451__490cbb_idx"
                    ),
                ],
            },
        ),
    ]
