# Generated by Django 5.0 on 2025-12-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0007_productlibrary_materialmapping_typelayer_typemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="NS3451Code",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="NS-3451 code (e.g., '222' for columns, '231' for external walls)",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Norwegian name", max_length=255)),
                (
                    "name_en",
                    models.CharField(
                        blank=True, help_text="English name", max_length=255, null=True
                    ),
                ),
                (
                    "guidance",
                    models.TextField(
                        blank=True, help_text="Usage guidance from standard", null=True
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        help_text="Hierarchy level (1=main category, 2=subcategory, 3=detail)"
                    ),
                ),
                (
                    "parent_code",
                    models.CharField(
                        blank=True,
                        help_text="Parent code for hierarchy",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "NS-3451 Code",
                "verbose_name_plural": "NS-3451 Codes",
                "db_table": "ns3451_codes",
                "ordering": ["code"],
            },
        ),
        migrations.AlterField(
            model_name="typemapping",
            name="ns3451_code",
            field=models.CharField(
                blank=True,
                help_text="NS-3451 building part code (e.g., '222')",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="typemapping",
            name="ns3451",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to NS-3451 code lookup",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="type_mappings",
                to="entities.ns3451code",
            ),
        ),
    ]
