# Generated by Django 5.0 on 2025-12-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0008_add_ns3451_reference_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ifcentity",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
