# Generated by Django 5.0 on 2025-12-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0009_change_entity_name_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="typemapping",
            name="discipline",
            field=models.CharField(
                blank=True,
                help_text="BIM discipline code (ARK, RIB, RIV, RIE, etc.)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="typemapping",
            name="representative_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pcs", "Piece count"),
                    ("m", "Linear meter"),
                    ("m2", "Square meter"),
                    ("m3", "Cubic meter"),
                ],
                help_text="Procurement-based representative unit (pcs, m, m2, m3)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="typemapping",
            name="mapping_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("mapped", "Mapped"),
                    ("ignored", "Ignored"),
                    ("review", "Needs Review"),
                    ("followup", "Follow-up"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
