# Generated by Django 5.0 on 2025-12-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0010_add_followup_status_and_fields"),
        (
            "models",
            "0009_model_fragments_generated_at_model_fragments_size_mb_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ifcentity",
            name="express_id",
            field=models.IntegerField(
                blank=True,
                help_text="IFC STEP file ID (express ID) - used for viewer selection",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="object_type",
            field=models.CharField(
                blank=True,
                help_text="IFC ObjectType - user-defined type string",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ifcentity",
            name="predefined_type",
            field=models.CharField(
                blank=True,
                help_text="IFC PredefinedType (STANDARD, NOTDEFINED, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["express_id"], name="ifc_entitie_express_1b7670_idx"
            ),
        ),
    ]
