# Generated by Django 5.0 on 2025-12-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0011_add_express_id_and_predefined_type"),
        ("models", "0010_add_version_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="ifcentity",
            name="is_removed",
            field=models.BooleanField(
                default=False,
                help_text="Soft delete: entity not present in latest model version",
            ),
        ),
        migrations.AddIndex(
            model_name="ifcentity",
            index=models.Index(
                fields=["is_removed"], name="ifc_entitie_is_remo_83458c_idx"
            ),
        ),
    ]
