# Generated by Django 5.0 on 2025-12-19 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0012_add_version_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeDefinitionLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "layer_order",
                    models.IntegerField(
                        help_text="Layer position (1 = exterior/outer, increasing inward)"
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        help_text="Material name (e.g., 'Gypsum board', 'Mineral wool')",
                        max_length=255,
                    ),
                ),
                (
                    "thickness_mm",
                    models.FloatField(help_text="Layer thickness in millimeters"),
                ),
                (
                    "epd_id",
                    models.CharField(
                        blank=True,
                        help_text="EPD database reference ID (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_mapping",
                    models.ForeignKey(
                        help_text="The type mapping (library entry) this layer belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definition_layers",
                        to="entities.typemapping",
                    ),
                ),
            ],
            options={
                "db_table": "type_definition_layers",
                "ordering": ["type_mapping", "layer_order"],
                "unique_together": {("type_mapping", "layer_order")},
            },
        ),
    ]
