# Generated by Django 6.0 on 2025-12-30 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0014_add_performance_indexes'),
        ('models', '0013_add_fragments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBankAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_type_name', models.CharField(help_text='The alternative type_name that maps to canonical', max_length=255)),
                ('alias_ifc_class', models.CharField(blank=True, help_text='IFC class for alias (if different from canonical)', max_length=100, null=True)),
                ('alias_source', models.CharField(blank=True, help_text='Which software/project produced this alias', max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'type_bank_aliases',
            },
        ),
        migrations.CreateModel(
            name='TypeBankEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ifc_class', models.CharField(help_text='IFC entity class (IfcWall, IfcColumn, etc.)', max_length=100)),
                ('type_name', models.CharField(blank=True, default='', help_text='From IfcTypeObject.Name (clean, no instance IDs)', max_length=255)),
                ('predefined_type', models.CharField(blank=True, default='NOTDEFINED', help_text='Schema enum: STANDARD, USERDEFINED, NOTDEFINED', max_length=50)),
                ('material', models.CharField(blank=True, default='', help_text='Primary IfcMaterial name from type', max_length=255)),
                ('ns3451_code', models.CharField(blank=True, help_text='NS-3451 building part code', max_length=20, null=True)),
                ('discipline', models.CharField(blank=True, help_text='BIM discipline code (ARK, RIB, RIV, RIE, etc.)', max_length=20, null=True)),
                ('canonical_name', models.CharField(blank=True, help_text='Human-readable normalized name', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('representative_unit', models.CharField(blank=True, choices=[('pcs', 'Piece count'), ('m', 'Linear meter'), ('m2', 'Square meter'), ('m3', 'Cubic meter')], help_text='Procurement-based unit (pcs, m, m2, m3)', max_length=10, null=True)),
                ('total_instance_count', models.IntegerField(default=0, help_text='Total instances observed across all models')),
                ('pct_is_external', models.FloatField(blank=True, help_text='% of instances with IsExternal=True', null=True)),
                ('pct_load_bearing', models.FloatField(blank=True, help_text='% of instances with LoadBearing=True', null=True)),
                ('pct_fire_rated', models.FloatField(blank=True, help_text='% of instances with non-empty FireRating', null=True)),
                ('source_model_count', models.IntegerField(default=1, help_text='How many models contributed observations')),
                ('mapping_status', models.CharField(choices=[('pending', 'Pending'), ('mapped', 'Mapped'), ('ignored', 'Ignored'), ('review', 'Needs Review'), ('followup', 'Follow-up')], default='pending', max_length=20)),
                ('confidence', models.CharField(blank=True, choices=[('auto', 'Auto-detected'), ('manual', 'Manually labeled'), ('verified', 'Expert verified'), ('disputed', 'Disputed')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('mapped_by', models.CharField(blank=True, max_length=255, null=True)),
                ('mapped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type Bank Entry',
                'verbose_name_plural': 'Type Bank Entries',
                'db_table': 'type_bank_entries',
            },
        ),
        migrations.CreateModel(
            name='TypeBankObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_count', models.IntegerField(default=0, help_text='Number of instances using this type in this model')),
                ('pct_is_external', models.FloatField(blank=True, null=True)),
                ('pct_load_bearing', models.FloatField(blank=True, null=True)),
                ('pct_fire_rated', models.FloatField(blank=True, null=True)),
                ('property_variations', models.JSONField(blank=True, default=dict, help_text="Property value distributions observed (e.g., {'IsExternal': {'True': 85, 'False': 15}})")),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'type_bank_observations',
            },
        ),
        migrations.RemoveIndex(
            model_name='changelog',
            name='change_log_change__332487_idx',
        ),
        migrations.RemoveIndex(
            model_name='changelog',
            name='change_log_ifc_gui_9d98d3_idx',
        ),
        migrations.RemoveField(
            model_name='storagemetrics',
            name='model',
        ),
        migrations.AlterUniqueTogether(
            name='typelayer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='typelayer',
            name='ifc_type',
        ),
        migrations.RemoveField(
            model_name='typelayer',
            name='material',
        ),
        migrations.RemoveIndex(
            model_name='ifctype',
            name='ifctype_model_idx',
        ),
        migrations.RemoveIndex(
            model_name='material',
            name='material_model_idx',
        ),
        migrations.RemoveIndex(
            model_name='materialassignment',
            name='matassign_ent_mat_idx',
        ),
        migrations.RemoveIndex(
            model_name='typeassignment',
            name='typeassign_ent_type_idx',
        ),
        migrations.AddField(
            model_name='typebankentry',
            name='ns3451',
            field=models.ForeignKey(blank=True, help_text='Reference to NS-3451 code lookup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_bank_entries', to='entities.ns3451code'),
        ),
        migrations.AddField(
            model_name='typebankalias',
            name='canonical',
            field=models.ForeignKey(help_text='The canonical type this is an alias for', on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='entities.typebankentry'),
        ),
        migrations.AddField(
            model_name='typebankobservation',
            name='source_model',
            field=models.ForeignKey(help_text='The model where this type was observed', on_delete=django.db.models.deletion.CASCADE, related_name='type_bank_observations', to='models.model'),
        ),
        migrations.AddField(
            model_name='typebankobservation',
            name='source_type',
            field=models.ForeignKey(help_text='The original IFCType record from this model', on_delete=django.db.models.deletion.CASCADE, related_name='type_bank_observation', to='entities.ifctype'),
        ),
        migrations.AddField(
            model_name='typebankobservation',
            name='type_bank_entry',
            field=models.ForeignKey(help_text='The canonical type this observation links to', on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='entities.typebankentry'),
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='model',
        ),
        migrations.RemoveField(
            model_name='changelog',
            name='previous_model',
        ),
        migrations.DeleteModel(
            name='StorageMetrics',
        ),
        migrations.DeleteModel(
            name='TypeLayer',
        ),
        migrations.AddIndex(
            model_name='typebankentry',
            index=models.Index(fields=['ifc_class'], name='type_bank_e_ifc_cla_eff138_idx'),
        ),
        migrations.AddIndex(
            model_name='typebankentry',
            index=models.Index(fields=['mapping_status'], name='type_bank_e_mapping_1403c6_idx'),
        ),
        migrations.AddIndex(
            model_name='typebankentry',
            index=models.Index(fields=['ns3451_code'], name='type_bank_e_ns3451__1e7c50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typebankentry',
            unique_together={('ifc_class', 'type_name', 'predefined_type', 'material')},
        ),
        migrations.AddIndex(
            model_name='typebankalias',
            index=models.Index(fields=['alias_type_name'], name='type_bank_a_alias_t_1c6a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='typebankobservation',
            index=models.Index(fields=['source_model'], name='type_bank_o_source__7719e3_idx'),
        ),
        migrations.AddIndex(
            model_name='typebankobservation',
            index=models.Index(fields=['observed_at'], name='type_bank_o_observe_6a1f41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typebankobservation',
            unique_together={('type_bank_entry', 'source_type')},
        ),
        migrations.DeleteModel(
            name='ChangeLog',
        ),
    ]
