# Generated by Django 6.0 on 2025-12-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_add_type_bank_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifctype',
            name='predefined_type',
            field=models.CharField(blank=True, help_text='IFC PredefinedType (STANDARD, USERDEFINED, NOTDEFINED)', max_length=50, null=True),
        ),
    ]
