# Generated by Django 6.0 on 2025-12-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_add_predefined_type_to_ifctype'),
        ('models', '0013_add_fragments_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifcentity',
            name='is_geometry_only',
            field=models.BooleanField(default=False, help_text='Entity has no type, name, or properties - geometry only (typically IfcBuildingElementProxy)'),
        ),
        migrations.AddField(
            model_name='processingreport',
            name='verification_data',
            field=models.JSONField(blank=True, default=dict, help_text='Verification stats from ifcopenshell parsing'),
        ),
        migrations.AddIndex(
            model_name='ifcentity',
            index=models.Index(fields=['is_geometry_only'], name='ifc_entitie_is_geom_d8b468_idx'),
        ),
    ]
