# Generated by Django 6.0 on 2025-12-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_add_data_quality_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ifctype',
            name='instance_count',
            field=models.IntegerField(default=0, help_text='Number of instances of this type in the model'),
        ),
    ]
