# Generated by Django 6.0 on 2026-01-25 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0019_add_has_ifc_type_object_field'),
        ('projects', '0002_projectconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeBankScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(choices=[('tfm', 'TFM (FM Marking)'), ('lca', 'LCA (Life Cycle Assessment)'), ('qto', 'QTO (Quantity Takeoff)'), ('clash', 'Clash Control'), ('custom', 'Custom')], help_text='What validation context this scope applies to', max_length=20)),
                ('scope_type_custom', models.CharField(blank=True, help_text="Custom scope type name (when scope_type='custom')", max_length=100, null=True)),
                ('status', models.CharField(choices=[('in', 'In Scope'), ('out', 'Out of Scope'), ('auto_excluded', 'Auto-excluded'), ('unknown', 'Unknown')], default='unknown', help_text='In/out of scope for this context', max_length=20)),
                ('reason', models.CharField(blank=True, help_text='Why this scope was assigned (config, auto_entity, auto_pattern, manual)', max_length=100, null=True)),
                ('comment', models.TextField(blank=True, help_text='User comment about scope decision', null=True)),
                ('validation_status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('missing', 'Missing'), ('dirty', 'Dirty (has data but should not)'), ('invalid', 'Invalid format'), ('na', 'Not applicable')], default='na', help_text='Validation status within this scope', max_length=20)),
                ('coverage', models.FloatField(blank=True, help_text='Coverage percentage (0.0-1.0) for scopes that track completeness', null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Project this scope is defined for', on_delete=django.db.models.deletion.CASCADE, related_name='type_scopes', to='projects.project')),
                ('type_bank_entry', models.ForeignKey(help_text='The type this scope applies to', on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='entities.typebankentry')),
            ],
            options={
                'verbose_name': 'Type Bank Scope',
                'verbose_name_plural': 'Type Bank Scopes',
                'db_table': 'type_bank_scopes',
                'indexes': [models.Index(fields=['scope_type'], name='type_bank_s_scope_t_7332a7_idx'), models.Index(fields=['status'], name='type_bank_s_status_4b2561_idx'), models.Index(fields=['validation_status'], name='type_bank_s_validat_5972af_idx')],
                'unique_together': {('type_bank_entry', 'project', 'scope_type')},
            },
        ),
    ]
