# Generated by Django 6.0 on 2026-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0020_typebankscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedefinitionlayer',
            name='material_unit',
            field=models.CharField(choices=[('m2', 'm²'), ('m', 'm'), ('m3', 'm³'), ('kg', 'kg'), ('pcs', 'pcs')], default='m2', help_text='Unit for this material quantity (must match EPD expected unit)', max_length=10),
        ),
        migrations.AddField(
            model_name='typedefinitionlayer',
            name='ns3457_code',
            field=models.CharField(blank=True, help_text='NS3457-8 material classification code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='typedefinitionlayer',
            name='ns3457_name',
            field=models.CharField(blank=True, help_text='NS3457-8 material name (auto-filled from code)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='typedefinitionlayer',
            name='quantity_per_unit',
            field=models.FloatField(default=1.0, help_text='Amount of this material per 1 type unit (e.g., 0.25 m³/m²)'),
        ),
        migrations.AddField(
            model_name='typemapping',
            name='type_category',
            field=models.CharField(choices=[('generic', 'Generic (early stage)'), ('specific', 'Specific (detailed design)'), ('product', 'Product (manufacturer)')], default='specific', help_text='Level of type specificity (generic/specific/product)', max_length=20),
        ),
        migrations.AlterField(
            model_name='typedefinitionlayer',
            name='thickness_mm',
            field=models.FloatField(blank=True, help_text='Visual thickness in mm for sandwich diagram (optional)', null=True),
        ),
    ]
