# Generated by Django 6.0 on 2026-02-05 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_add_material_inventory_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Material name (e.g., 'Concrete B35')", max_length=255)),
                ('category', models.CharField(choices=[('steel_structural', 'Structural Steel'), ('rebar', 'Reinforcement Steel'), ('concrete_cast', 'Cast-in-place Concrete'), ('concrete_hollowcore', 'Hollow Core Slab'), ('wood_glulam', 'Glulam'), ('wood_clt', 'CLT/Massivtre'), ('wood_structural', 'Structural Timber'), ('wood_treated', 'Treated Wood'), ('gypsum_standard', 'Gypsum Board Standard'), ('gypsum_wetroom', 'Gypsum Board Wetroom'), ('osb', 'OSB Board'), ('chipboard', 'Chipboard'), ('mineral_wool_inner', 'Mineral Wool Inner Wall'), ('mineral_wool_outer', 'Mineral Wool Outer Wall'), ('mineral_wool_roof', 'Mineral Wool Roof'), ('glass_wool', 'Glass Wool'), ('insulation_eps', 'EPS Insulation'), ('insulation_xps', 'XPS Insulation'), ('paint_interior', 'Interior Paint'), ('paint_exterior', 'Exterior Paint'), ('tile_ceramic', 'Ceramic Tile'), ('tile_adhesive', 'Tile Adhesive'), ('parquet', 'Parquet'), ('linoleum', 'Linoleum'), ('vinyl', 'Vinyl Flooring'), ('carpet', 'Carpet'), ('screed', 'Screed/Levelling'), ('vapor_barrier', 'Vapor Barrier'), ('wetroom_membrane', 'Wetroom Membrane'), ('pvc_roof', 'PVC Roofing'), ('window', 'Window'), ('door_interior', 'Interior Door'), ('glass_facade', 'Glass Facade'), ('glass_wall_interior', 'Interior Glass Wall'), ('block_lightweight', 'Lightweight Block'), ('brick', 'Brick'), ('aggregate', 'Aggregate/Pukk'), ('aluminium', 'Aluminium'), ('copper', 'Copper'), ('pvc_pipe', 'PVC (pipes)'), ('pe_pipe', 'PE (pipes)'), ('other', 'Other')], help_text='Material category (aligned with Enova EPD)', max_length=50)),
                ('unit', models.CharField(choices=[('m3', 'm³'), ('m2', 'm²'), ('m', 'm'), ('kg', 'kg')], help_text='Unit for LCA calculations', max_length=10)),
                ('density_kg_m3', models.FloatField(blank=True, help_text='Material density in kg/m³', null=True)),
                ('thermal_conductivity', models.FloatField(blank=True, help_text='Thermal conductivity W/(m·K)', null=True)),
                ('normalized_epd_id', models.CharField(blank=True, help_text='Generic/Reduzer EPD reference', max_length=100, null=True)),
                ('specific_epd_id', models.CharField(blank=True, help_text='Product-specific EPD reference (optional)', max_length=100, null=True)),
                ('gwp_a1_a3', models.FloatField(blank=True, help_text='Global Warming Potential A1-A3 (kgCO2e per unit)', null=True)),
                ('reduzer_product_id', models.CharField(blank=True, help_text="Reduzer ProductID (e.g., 'Reduzer Enova Gipsplate normal - typisk verdi')", max_length=255, null=True)),
                ('reduzer_product_id_type', models.CharField(blank=True, help_text='ProductID type: EPDno, NOBB, NEPD, GTINFPAK', max_length=20, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer_product_id', models.CharField(blank=True, max_length=100, null=True)),
                ('reused_status', models.CharField(choices=[('new', 'New'), ('existing_kept', 'Existing Kept'), ('reused', 'Reused'), ('existing_waste', 'Existing Waste')], default='new', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text="Data source: 'enova', 'magna-reduzer', 'manual', 'ifc'", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Library Entry',
                'verbose_name_plural': 'Material Library',
                'db_table': 'material_library',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='product_library',
            field=models.ForeignKey(blank=True, help_text='Specific product (for specs, dimensions, manufacturer)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ifc_materials', to='entities.productlibrary'),
        ),
        migrations.AddField(
            model_name='material',
            name='reused_status',
            field=models.CharField(choices=[('new', 'New'), ('existing_kept', 'Existing Kept'), ('reused', 'Reused'), ('existing_waste', 'Existing Waste')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='datasheet_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='dimensions',
            field=models.JSONField(blank=True, default=dict, help_text='Dimensions: {width, height, depth, weight, thickness}'),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='is_composite',
            field=models.BooleanField(default=False, help_text='True if product contains multiple materials (use ProductComposition)'),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='manufacturer_product_id',
            field=models.CharField(blank=True, help_text="Manufacturer's product ID/SKU", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='material_category',
            field=models.CharField(blank=True, choices=[('steel_structural', 'Structural Steel'), ('rebar', 'Reinforcement Steel'), ('concrete_cast', 'Cast-in-place Concrete'), ('concrete_hollowcore', 'Hollow Core Slab'), ('wood_glulam', 'Glulam'), ('wood_clt', 'CLT/Massivtre'), ('wood_structural', 'Structural Timber'), ('wood_treated', 'Treated Wood'), ('gypsum_standard', 'Gypsum Board Standard'), ('gypsum_wetroom', 'Gypsum Board Wetroom'), ('osb', 'OSB Board'), ('chipboard', 'Chipboard'), ('mineral_wool_inner', 'Mineral Wool Inner Wall'), ('mineral_wool_outer', 'Mineral Wool Outer Wall'), ('mineral_wool_roof', 'Mineral Wool Roof'), ('glass_wool', 'Glass Wool'), ('insulation_eps', 'EPS Insulation'), ('insulation_xps', 'XPS Insulation'), ('paint_interior', 'Interior Paint'), ('paint_exterior', 'Exterior Paint'), ('tile_ceramic', 'Ceramic Tile'), ('tile_adhesive', 'Tile Adhesive'), ('parquet', 'Parquet'), ('linoleum', 'Linoleum'), ('vinyl', 'Vinyl Flooring'), ('carpet', 'Carpet'), ('screed', 'Screed/Levelling'), ('vapor_barrier', 'Vapor Barrier'), ('wetroom_membrane', 'Wetroom Membrane'), ('pvc_roof', 'PVC Roofing'), ('window', 'Window'), ('door_interior', 'Interior Door'), ('glass_facade', 'Glass Facade'), ('glass_wall_interior', 'Interior Glass Wall'), ('block_lightweight', 'Lightweight Block'), ('brick', 'Brick'), ('aggregate', 'Aggregate/Pukk'), ('aluminium', 'Aluminium'), ('copper', 'Copper'), ('pvc_pipe', 'PVC (pipes)'), ('pe_pipe', 'PE (pipes)'), ('other', 'Other')], help_text='Primary material category (for homogeneous products)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='reduzer_product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='reduzer_product_id_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='reused_status',
            field=models.CharField(choices=[('new', 'New'), ('existing_kept', 'Existing Kept'), ('reused', 'Reused'), ('existing_waste', 'Existing Waste')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='productlibrary',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible spec storage from datasheet'),
        ),
        migrations.AlterField(
            model_name='productlibrary',
            name='category',
            field=models.CharField(blank=True, help_text='Product category (window, door, fixture, etc.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='typedefinitionlayer',
            name='material_name',
            field=models.CharField(help_text='Material name for display (kept for backwards compat)', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='material_library',
            field=models.ForeignKey(blank=True, help_text='Normalized material category (for LCA, density, EPD)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ifc_materials', to='entities.materiallibrary'),
        ),
        migrations.AddField(
            model_name='typedefinitionlayer',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Link to global MaterialLibrary entry (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_layers', to='entities.materiallibrary'),
        ),
        migrations.CreateModel(
            name='ProductComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(help_text='Amount per 1 product unit')),
                ('unit', models.CharField(choices=[('m3', 'm³'), ('m2', 'm²'), ('m', 'm'), ('kg', 'kg')], help_text='Unit for this quantity (kg, m², m³)', max_length=10)),
                ('layer_order', models.IntegerField(blank=True, help_text='Layer position for layered products', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_uses', to='entities.materiallibrary')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='entities.productlibrary')),
            ],
            options={
                'verbose_name': 'Product Composition',
                'verbose_name_plural': 'Product Compositions',
                'db_table': 'product_compositions',
                'ordering': ['product', 'layer_order'],
            },
        ),
    ]
