# Generated by Django 6.0 on 2026-02-05 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0022_add_material_product_libraries'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='PA0802 code: AB, AD, AV, etc.', max_length=4, unique=True)),
                ('name_no', models.CharField(help_text='Norwegian name', max_length=100)),
                ('name_en', models.CharField(help_text='English name', max_length=100)),
                ('category', models.CharField(help_text='Category: A-Structural, D-Openings, E-Cladding, etc.', max_length=50)),
                ('canonical_ifc_class', models.CharField(help_text='Primary expected IFC class: IfcBeam, IfcWall, etc.', max_length=50)),
                ('alternative_ifc_classes', models.JSONField(blank=True, default=list, help_text="Alternative valid IFC classes: ['IfcBeamStandardCase']")),
                ('suggested_ns3451_codes', models.JSONField(blank=True, default=list, help_text="Suggested NS3451 codes: ['223', '2231']")),
                ('name_patterns', models.JSONField(blank=True, default=list, help_text="Glob patterns for name matching: ['*beam*', '*bjelke*']")),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semantic Type',
                'verbose_name_plural': 'Semantic Types',
                'db_table': 'semantic_types',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.AddField(
            model_name='typebankentry',
            name='semantic_type_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score (0.0-1.0) for auto-assigned types', null=True),
        ),
        migrations.AddField(
            model_name='typebankentry',
            name='semantic_type_source',
            field=models.CharField(blank=True, choices=[('auto_rule', 'Auto: IFC Class Rule'), ('auto_pattern', 'Auto: Name Pattern'), ('manual', 'Manual Assignment'), ('verified', 'Verified by User')], help_text='How the semantic type was assigned', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='typebankentry',
            name='semantic_type',
            field=models.ForeignKey(blank=True, help_text='Canonical semantic type (what this element ACTUALLY is)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_bank_entries', to='entities.semantictype'),
        ),
        migrations.CreateModel(
            name='SemanticTypeIFCMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifc_class', models.CharField(help_text='IFC class: IfcWall, IfcBuildingElementProxy, etc.', max_length=50)),
                ('predefined_type', models.CharField(blank=True, default='', help_text='Optional PredefinedType filter', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='True if this is the expected/correct IFC class')),
                ('is_common_misuse', models.BooleanField(default=False, help_text='True if this IFC class is commonly misused for this type')),
                ('confidence_hint', models.FloatField(default=0.5, help_text='Confidence when auto-detected via this mapping (0.0-1.0)')),
                ('note', models.TextField(blank=True, help_text='Explanation of this mapping', null=True)),
                ('semantic_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifc_mappings', to='entities.semantictype')),
            ],
            options={
                'verbose_name': 'Semantic Type IFC Mapping',
                'verbose_name_plural': 'Semantic Type IFC Mappings',
                'db_table': 'semantic_type_ifc_mappings',
                'indexes': [models.Index(fields=['ifc_class'], name='semantic_ty_ifc_cla_f21e26_idx')],
                'unique_together': {('semantic_type', 'ifc_class', 'predefined_type')},
            },
        ),
    ]
