# Generated by Django 6.0 on 2026-02-07 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0023_semantic_type_normalization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typebankentry',
            name='flag_reason',
            field=models.TextField(blank=True, help_text="Reason for flagging (required when verification_status='flagged')", null=True),
        ),
        migrations.AddField(
            model_name='typebankentry',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('auto', 'Auto-classified'), ('verified', 'Verified'), ('flagged', 'Flagged')], default='pending', help_text='Human verification status: pending/auto/verified/flagged', max_length=20),
        ),
        migrations.AddField(
            model_name='typebankentry',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the entry was verified or flagged', null=True),
        ),
        migrations.AddField(
            model_name='typebankentry',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified or flagged this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_type_bank_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='typemapping',
            name='flag_reason',
            field=models.TextField(blank=True, help_text="Reason for flagging (required when verification_status='flagged')", null=True),
        ),
        migrations.AddField(
            model_name='typemapping',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('auto', 'Auto-classified'), ('verified', 'Verified'), ('flagged', 'Flagged')], default='pending', help_text='Human verification status: pending/auto/verified/flagged', max_length=20),
        ),
        migrations.AddField(
            model_name='typemapping',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the mapping was verified or flagged', null=True),
        ),
        migrations.AddField(
            model_name='typemapping',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified or flagged this mapping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_type_mappings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='typebankentry',
            index=models.Index(fields=['verification_status'], name='type_bank_e_verific_d5b694_idx'),
        ),
        migrations.AddIndex(
            model_name='typemapping',
            index=models.Index(fields=['verification_status'], name='type_mappin_verific_6c5e47_idx'),
        ),
    ]
