# Generated by Django 6.0 on 2026-02-07 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0024_add_verification_status'),
        ('models', '0013_add_fragments_status'),
        ('projects', '0002_projectconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiallibrary',
            name='gwp_a1_a3',
        ),
        migrations.RemoveField(
            model_name='materiallibrary',
            name='normalized_epd_id',
        ),
        migrations.RemoveField(
            model_name='materiallibrary',
            name='reduzer_product_id',
        ),
        migrations.RemoveField(
            model_name='materiallibrary',
            name='reduzer_product_id_type',
        ),
        migrations.RemoveField(
            model_name='materiallibrary',
            name='specific_epd_id',
        ),
        migrations.RemoveField(
            model_name='productlibrary',
            name='epd_data',
        ),
        migrations.RemoveField(
            model_name='productlibrary',
            name='reduzer_product_id',
        ),
        migrations.RemoveField(
            model_name='productlibrary',
            name='reduzer_product_id_type',
        ),
        migrations.AlterField(
            model_name='materiallibrary',
            name='category',
            field=models.CharField(choices=[('steel_structural', 'Structural Steel'), ('rebar', 'Reinforcement Steel'), ('concrete_cast', 'Cast-in-place Concrete'), ('concrete_hollowcore', 'Hollow Core Slab'), ('wood_glulam', 'Glulam'), ('wood_clt', 'CLT/Massivtre'), ('wood_structural', 'Structural Timber'), ('wood_treated', 'Treated Wood'), ('gypsum_standard', 'Gypsum Board Standard'), ('gypsum_wetroom', 'Gypsum Board Wetroom'), ('osb', 'OSB Board'), ('chipboard', 'Chipboard'), ('mineral_wool_inner', 'Mineral Wool Inner Wall'), ('mineral_wool_outer', 'Mineral Wool Outer Wall'), ('mineral_wool_roof', 'Mineral Wool Roof'), ('glass_wool', 'Glass Wool'), ('insulation_eps', 'EPS Insulation'), ('insulation_xps', 'XPS Insulation'), ('paint_interior', 'Interior Paint'), ('paint_exterior', 'Exterior Paint'), ('tile_ceramic', 'Ceramic Tile'), ('tile_adhesive', 'Tile Adhesive'), ('parquet', 'Parquet'), ('linoleum', 'Linoleum'), ('vinyl', 'Vinyl Flooring'), ('carpet', 'Carpet'), ('screed', 'Screed/Levelling'), ('vapor_barrier', 'Vapor Barrier'), ('wetroom_membrane', 'Wetroom Membrane'), ('pvc_roof', 'PVC Roofing'), ('window', 'Window'), ('door_interior', 'Interior Door'), ('glass_facade', 'Glass Facade'), ('glass_wall_interior', 'Interior Glass Wall'), ('block_lightweight', 'Lightweight Block'), ('brick', 'Brick'), ('aggregate', 'Aggregate/Pukk'), ('aluminium', 'Aluminium'), ('copper', 'Copper'), ('pvc_pipe', 'PVC (pipes)'), ('pe_pipe', 'PE (pipes)'), ('other', 'Other')], help_text='Material category (aligned with Enova classification)', max_length=50),
        ),
        migrations.CreateModel(
            name='EPDLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('reduzer', 'Reduzer'), ('oneclick', 'OneClickLCA'), ('nepd', 'NEPD'), ('epd_norge', 'EPD Norge'), ('custom', 'Custom')], help_text='EPD database source', max_length=50)),
                ('source_id', models.CharField(help_text='ID in source system (e.g., Reduzer product name)', max_length=255)),
                ('name', models.CharField(help_text='Human-readable EPD name', max_length=500)),
                ('category', models.CharField(blank=True, help_text='Enova category or similar classification', max_length=100, null=True)),
                ('gwp_a1_a3', models.FloatField(blank=True, help_text='GWP A1-A3: Product stage (kg CO2e per declared unit)', null=True)),
                ('gwp_c3_c4', models.FloatField(blank=True, help_text='GWP C3-C4: End of life (kg CO2e per declared unit)', null=True)),
                ('gwp_d', models.FloatField(blank=True, help_text='GWP D: Benefits beyond system boundary (kg CO2e per declared unit)', null=True)),
                ('gwp_total', models.FloatField(blank=True, help_text='Total GWP (A1-A3 + C3-C4 + D, or as declared)', null=True)),
                ('unit', models.CharField(help_text='Base unit: kg, m², m³, pcs', max_length=20)),
                ('declared_unit', models.CharField(blank=True, help_text="Full declared unit (e.g., '1 m²', '1000 kg')", max_length=100, null=True)),
                ('valid_until', models.DateField(blank=True, help_text='EPD expiration date', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional EPD data (manufacturer, program operator, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EPD Library Entry',
                'verbose_name_plural': 'EPD Library',
                'db_table': 'epd_library',
                'ordering': ['source', 'name'],
                'indexes': [models.Index(fields=['source'], name='epd_library_source_ec66a2_idx'), models.Index(fields=['category'], name='epd_library_categor_ed385b_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='EPDMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('ifc_type', 'IFC Type'), ('ifc_material', 'IFC Material'), ('material_lib', 'Material Library'), ('product_lib', 'Product Library')], help_text='What this EPD is mapped to', max_length=50)),
                ('target_id', models.UUIDField(help_text='UUID of the target (IFCType, Material, MaterialLibrary, or ProductLibrary)')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority = preferred when multiple mappings exist')),
                ('notes', models.TextField(blank=True, help_text='Reason for this mapping or additional context', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epd_mappings', to=settings.AUTH_USER_MODEL)),
                ('epd', models.ForeignKey(help_text='The EPD to use for this target', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='entities.epdlibrary')),
                ('project', models.ForeignKey(blank=True, help_text='Project-specific mapping (null = global default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epd_mappings', to='projects.project')),
            ],
            options={
                'verbose_name': 'EPD Mapping',
                'verbose_name_plural': 'EPD Mappings',
                'db_table': 'epd_mappings',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='epd_mapping_target__7ee69f_idx'), models.Index(fields=['project'], name='epd_mapping_project_4e082c_idx')],
            },
        ),
        migrations.CreateModel(
            name='IFCMaterialNormalization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ifc_material_name', models.CharField(help_text='Raw material name from IFC (exact match or pattern)', max_length=500)),
                ('normalized_name', models.CharField(blank=True, help_text='Canonical name (can differ from MaterialLibrary.name)', max_length=255, null=True)),
                ('confidence', models.CharField(choices=[('auto', 'Auto-detected'), ('manual', 'Manual'), ('verified', 'Verified')], default='auto', help_text='How this normalization was created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_library', models.ForeignKey(blank=True, help_text='Normalized MaterialLibrary entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalizations', to='entities.materiallibrary')),
                ('model', models.ForeignKey(blank=True, help_text='Model-specific normalization (null = global rule)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_normalizations', to='models.model')),
            ],
            options={
                'verbose_name': 'IFC Material Normalization',
                'verbose_name_plural': 'IFC Material Normalizations',
                'db_table': 'ifc_material_normalizations',
                'indexes': [models.Index(fields=['ifc_material_name'], name='ifc_materia_ifc_mat_693a8e_idx'), models.Index(fields=['confidence'], name='ifc_materia_confide_613944_idx')],
                'unique_together': {('model', 'ifc_material_name')},
            },
        ),
    ]
