# Generated by Django 6.0 on 2026-02-07 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_add_epd_architecture'),
        ('models', '0013_add_fragments_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typebankobservation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='typebankobservation',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this observation became historical (source deleted)', null=True),
        ),
        migrations.AddField(
            model_name='typebankobservation',
            name='is_historical',
            field=models.BooleanField(default=False, help_text='True if source model/type was deleted - observation preserved for audit trail'),
        ),
        migrations.AlterField(
            model_name='typebankobservation',
            name='source_model',
            field=models.ForeignKey(blank=True, help_text='The model where this type was observed (null if model deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_bank_observations', to='models.model'),
        ),
        migrations.AlterField(
            model_name='typebankobservation',
            name='source_type',
            field=models.ForeignKey(blank=True, help_text='The original IFCType record from this model (null if type deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_bank_observation', to='entities.ifctype'),
        ),
        migrations.AddIndex(
            model_name='typebankobservation',
            index=models.Index(fields=['is_historical'], name='type_bank_o_is_hist_b68125_idx'),
        ),
        migrations.AddIndex(
            model_name='typebankobservation',
            index=models.Index(fields=['type_bank_entry', 'is_historical'], name='type_bank_o_type_ba_5cf84d_idx'),
        ),
    ]
