# Generated by Django 6.0 on 2026-02-07 22:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0026_sprint2_vault_immutable_audit'),
        ('models', '0014_sprint1_gatekeeper_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='NS3451OwnershipMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discipline', models.CharField(choices=[('ARK', 'Architecture'), ('RIB', 'Structural'), ('RIV', 'Mechanical/HVAC'), ('RIE', 'Electrical'), ('LARK', 'Landscape'), ('RIG', 'Geotechnical')], help_text='BIM discipline code', max_length=10)),
                ('ownership_level', models.CharField(choices=[('primary', 'Primary - Must model'), ('secondary', 'Secondary - May model'), ('reference', 'Reference - Copy from others')], help_text='Level of ownership for this discipline', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional guidance for this assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NS3451 Ownership Matrix',
                'verbose_name_plural': 'NS3451 Ownership Matrix',
                'db_table': 'ns3451_ownership_matrix',
                'ordering': ['ns3451_code', 'discipline'],
            },
        ),
        migrations.AddField(
            model_name='ifctype',
            name='ownership_status',
            field=models.CharField(choices=[('primary', 'Primary - My discipline owns this type'), ('reference', 'Reference - Other discipline owns, I copy'), ('ghost', 'Ghost - Ignore for verification (not my concern)')], default='primary', help_text='Discipline ownership: primary (my type), reference (copy from others), ghost (ignore)', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ifctype',
            index=models.Index(fields=['ownership_status'], name='ifc_types_ownersh_133bc0_idx'),
        ),
        migrations.AddField(
            model_name='ns3451ownershipmatrix',
            name='ns3451_code',
            field=models.ForeignKey(help_text='NS3451 building part code', on_delete=django.db.models.deletion.CASCADE, related_name='ownership_matrix', to='entities.ns3451code'),
        ),
        migrations.AddIndex(
            model_name='ns3451ownershipmatrix',
            index=models.Index(fields=['discipline'], name='ns3451_owne_discipl_5929f7_idx'),
        ),
        migrations.AddIndex(
            model_name='ns3451ownershipmatrix',
            index=models.Index(fields=['ownership_level'], name='ns3451_owne_ownersh_45a61d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ns3451ownershipmatrix',
            unique_together={('ns3451_code', 'discipline')},
        ),
    ]
