# Generated by Django 6.0 on 2026-02-07 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0027_sprint1_gatekeeper_ownership'),
        ('models', '0014_sprint1_gatekeeper_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('basepoint_x', models.FloatField(help_text='Entity centroid X coordinate')),
                ('basepoint_y', models.FloatField(help_text='Entity centroid Y coordinate')),
                ('basepoint_z', models.FloatField(help_text='Entity centroid Z coordinate')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence: 1.0 = point clearly inside, <1.0 = near boundary/estimated')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(help_text='The discrete entity being assigned to a room', on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='entities.ifcentity')),
                ('entity_model', models.ForeignKey(help_text='Model containing the entity (typically MEP)', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_room_assignments', to='models.model')),
                ('room', models.ForeignKey(help_text='The IfcSpace (room) containing this entity', on_delete=django.db.models.deletion.CASCADE, related_name='contained_entities', to='entities.ifcentity')),
                ('room_model', models.ForeignKey(help_text='Model containing the room (typically ARK)', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_room_assignments', to='models.model')),
            ],
            options={
                'verbose_name': 'Room Assignment',
                'verbose_name_plural': 'Room Assignments',
                'db_table': 'room_assignments',
                'indexes': [models.Index(fields=['entity_model'], name='room_assign_entity__341fb4_idx'), models.Index(fields=['room_model'], name='room_assign_room_mo_88b718_idx'), models.Index(fields=['confidence'], name='room_assign_confide_48c16a_idx')],
                'unique_together': {('entity', 'room')},
            },
        ),
    ]
