# Generated by Django 6.0 on 2026-02-14 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0028_sprint3_mapper_room_assignment'),
        ('models', '0014_sprint1_gatekeeper_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ifc_schema', models.CharField(max_length=20)),
                ('file_size_mb', models.FloatField(blank=True, null=True)),
                ('application', models.CharField(blank=True, max_length=255)),
                ('total_types', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_storeys', models.IntegerField(default=0)),
                ('total_spaces', models.IntegerField(default=0)),
                ('duplicate_guid_count', models.IntegerField(default=0)),
                ('units', models.JSONField(default=dict)),
                ('coordinates', models.JSONField(default=dict)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('building_name', models.CharField(blank=True, max_length=255)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='models.model')),
            ],
            options={
                'db_table': 'model_analysis',
            },
        ),
        migrations.CreateModel(
            name='AnalysisType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_class', models.CharField(max_length=100)),
                ('type_name', models.CharField(blank=True, max_length=500, null=True)),
                ('element_class', models.CharField(blank=True, max_length=100)),
                ('predefined_type', models.CharField(blank=True, max_length=50, null=True)),
                ('instance_count', models.IntegerField(default=0)),
                ('is_empty', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_untyped', models.BooleanField(default=False)),
                ('loadbearing_true', models.IntegerField(default=0)),
                ('loadbearing_false', models.IntegerField(default=0)),
                ('loadbearing_unset', models.IntegerField(default=0)),
                ('is_external_true', models.IntegerField(default=0)),
                ('is_external_false', models.IntegerField(default=0)),
                ('is_external_unset', models.IntegerField(default=0)),
                ('fire_rating_set', models.IntegerField(default=0)),
                ('fire_rating_unset', models.IntegerField(default=0)),
                ('primary_representation', models.CharField(blank=True, max_length=100)),
                ('mapped_item_count', models.IntegerField(default=0)),
                ('mapped_source_count', models.IntegerField(default=0)),
                ('reuse_ratio', models.FloatField(blank=True, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('ifc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_data', to='entities.ifctype')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='entities.modelanalysis')),
            ],
            options={
                'db_table': 'analysis_types',
            },
        ),
        migrations.CreateModel(
            name='AnalysisStorey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('element_count', models.IntegerField(default=0)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storeys', to='entities.modelanalysis')),
            ],
            options={
                'db_table': 'analysis_storeys',
            },
        ),
        migrations.CreateModel(
            name='AnalysisTypeStorey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_count', models.IntegerField(default=0)),
                ('storey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_distribution', to='entities.analysisstorey')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storey_distribution', to='entities.analysistype')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_storeys', to='entities.modelanalysis')),
            ],
            options={
                'db_table': 'analysis_type_storeys',
                'unique_together': {('type', 'storey')},
            },
        ),
        migrations.AddIndex(
            model_name='analysistype',
            index=models.Index(fields=['type_class'], name='analysis_ty_type_cl_63733c_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistype',
            index=models.Index(fields=['element_class'], name='analysis_ty_element_3bbe62_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistype',
            index=models.Index(fields=['is_untyped'], name='analysis_ty_is_unty_6c356c_idx'),
        ),
        migrations.AddIndex(
            model_name='analysistype',
            index=models.Index(fields=['is_proxy'], name='analysis_ty_is_prox_f0d274_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisstorey',
            unique_together={('analysis', 'name')},
        ),
    ]
