# Generated by Django 6.0 on 2026-02-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0029_modelanalysis_analysistype_analysisstorey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ns3451ownershipmatrix',
            name='discipline',
            field=models.CharField(choices=[('ARK', 'Architecture'), ('RIB', 'Structural'), ('RIBp', 'Structural Prefab'), ('RIG', 'Geotechnical'), ('RIV', 'HVAC'), ('RIVv', 'Ventilation'), ('RIVp', 'Plumbing'), ('RIVspr', 'Sprinkler'), ('RIkulde', 'Cooling'), ('RIvarme', 'Heating'), ('RIE', 'Electrical'), ('LARK', 'Landscape'), ('RIA', 'Acoustics'), ('RIBr', 'Fire Safety'), ('RIByfy', 'Building Physics'), ('RIM', 'Environmental'), ('BIM-K', 'BIM Coordinator'), ('BIM-M', 'BIM Manager'), ('PGL', 'Design Manager'), ('PM', 'Project Manager'), ('BH', 'Owner/Client')], help_text='BIM discipline code', max_length=20),
        ),
    ]
