# Generated by Django 6.0 on 2026-03-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0030_alter_ns3451ownershipmatrix_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemapping',
            name='verification_issues',
            field=models.JSONField(blank=True, default=list, help_text='Issues from last engine verification: [{rule_id, severity, message}]'),
        ),
        migrations.AddField(
            model_name='typemapping',
            name='verified_engine_at',
            field=models.DateTimeField(blank=True, help_text='When the verification engine last ran on this type', null=True),
        ),
    ]
