# Generated by Django 6.0 on 2026-03-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0031_verification_engine_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelanalysis',
            name='spatial_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
