# Generated by Django 5.0 on 2026-04-29 03:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0034_drop_processing_report"),
        ("models", "0021_add_discovered_grid"),
        ("projects", "0005_add_project_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawingRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ref1_paper_x", models.FloatField(help_text="mm from sheet origin")),
                ("ref1_paper_y", models.FloatField(help_text="mm from sheet origin")),
                (
                    "ref1_grid_u",
                    models.CharField(help_text='U-axis tag (e.g. "A")', max_length=10),
                ),
                (
                    "ref1_grid_v",
                    models.CharField(help_text='V-axis tag (e.g. "3")', max_length=10),
                ),
                ("ref2_paper_x", models.FloatField()),
                ("ref2_paper_y", models.FloatField()),
                ("ref2_grid_u", models.CharField(max_length=10)),
                ("ref2_grid_v", models.CharField(max_length=10)),
                (
                    "transform_matrix",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="3x3 affine transform (paper-mm -> model-meters), row-major",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "drawing_registrations",
            },
        ),
        migrations.CreateModel(
            name="DrawingSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_index",
                    models.IntegerField(
                        default=0,
                        help_text="0-based page index within the source file (always 0 for DXF/DWG)",
                    ),
                ),
                (
                    "sheet_number",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("sheet_name", models.CharField(blank=True, max_length=255)),
                ("width_mm", models.FloatField(blank=True, null=True)),
                ("height_mm", models.FloatField(blank=True, null=True)),
                (
                    "scale",
                    models.CharField(
                        blank=True,
                        help_text="Drawing scale as text (e.g. '1:50'). Free-form because exporters disagree.",
                        max_length=50,
                    ),
                ),
                (
                    "title_block_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed against TitleBlockTemplate.fields. {field_name: value}",
                    ),
                ),
                (
                    "raw_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Format-specific metadata (DXF layers, PDF outline, etc.)",
                    ),
                ),
            ],
            options={
                "db_table": "drawing_sheets",
                "ordering": ["source_file_id", "page_index"],
            },
        ),
        migrations.CreateModel(
            name="TitleBlockTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {name, label, region: {x,y,w,h}, type, maps_to?} entries",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-applied to new drawings in this project when set",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "title_block_templates",
                "ordering": ["project_id", "name"],
            },
        ),
        migrations.AddField(
            model_name="drawingregistration",
            name="grid_source_run",
            field=models.ForeignKey(
                blank=True,
                help_text="ExtractionRun whose discovered_grid was used to resolve grid labels",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registrations_using",
                to="models.extractionrun",
            ),
        ),
        migrations.AddField(
            model_name="drawingsheet",
            name="extraction_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing_sheets",
                to="models.extractionrun",
            ),
        ),
        migrations.AddField(
            model_name="drawingsheet",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="drawing_sheets",
                to="projects.projectscope",
            ),
        ),
        migrations.AddField(
            model_name="drawingsheet",
            name="source_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing_sheets",
                to="models.sourcefile",
            ),
        ),
        migrations.AddField(
            model_name="drawingregistration",
            name="drawing_sheet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registration",
                to="entities.drawingsheet",
            ),
        ),
        migrations.AddField(
            model_name="titleblocktemplate",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="title_block_templates",
                to="projects.project",
            ),
        ),
        migrations.AddIndex(
            model_name="drawingsheet",
            index=models.Index(
                fields=["source_file", "page_index"],
                name="drawing_she_source__a4eb5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="drawingsheet",
            index=models.Index(fields=["scope"], name="drawing_she_scope_i_343b00_idx"),
        ),
        migrations.AddConstraint(
            model_name="drawingsheet",
            constraint=models.UniqueConstraint(
                fields=("source_file", "page_index"), name="uniq_drawing_sheet_per_page"
            ),
        ),
        migrations.AddConstraint(
            model_name="titleblocktemplate",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="uniq_titleblock_per_project_name"
            ),
        ),
    ]
