# Generated by Django 5.0 on 2026-04-29 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0035_add_drawing_models"),
        ("models", "0021_add_discovered_grid"),
        ("projects", "0005_add_project_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_index",
                    models.IntegerField(
                        default=0,
                        help_text="0-based page index for per-page PDF extraction; 0 for whole-file formats",
                    ),
                ),
                (
                    "markdown_content",
                    models.TextField(
                        blank=True, help_text="Unified markdown body for PDF/DOCX/PPTX"
                    ),
                ),
                (
                    "structured_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Typed JSON for XLSX/CSV: {"sheets": [{"name", "columns", "rows", "types"}]}',
                    ),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        default=1,
                        help_text="Total page/slide/sheet count in the source document",
                    ),
                ),
                (
                    "structure",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Sections, headings, tables: {"headings": [...], "tables": [...]}',
                    ),
                ),
                (
                    "extracted_images",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of {url?, page, description?} entries",
                    ),
                ),
                (
                    "search_text",
                    models.TextField(
                        blank=True,
                        help_text="Normalized text for full-text search (lowercased, whitespace-collapsed)",
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        choices=[
                            ("text_layer", "PDF text layer"),
                            ("ocr", "OCR"),
                            ("structured", "Structured (DOCX/XLSX/PPTX)"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="structured",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "document_contents",
                "ordering": ["source_file_id", "page_index"],
            },
        ),
        migrations.RenameIndex(
            model_name="propertyset",
            new_name="property_se_value_b_30e8f1_idx",
            old_name="property_se_value_b_idx",
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="extraction_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_contents",
                to="models.extractionrun",
            ),
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_contents",
                to="projects.projectscope",
            ),
        ),
        migrations.AddField(
            model_name="documentcontent",
            name="source_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_contents",
                to="models.sourcefile",
            ),
        ),
        migrations.AddIndex(
            model_name="documentcontent",
            index=models.Index(
                fields=["source_file", "page_index"],
                name="document_co_source__2f1854_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentcontent",
            index=models.Index(fields=["scope"], name="document_co_scope_i_72a03c_idx"),
        ),
        migrations.AddIndex(
            model_name="documentcontent",
            index=models.Index(
                fields=["extraction_method"], name="document_co_extract_2048a3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentcontent",
            constraint=models.UniqueConstraint(
                fields=("source_file", "extraction_run", "page_index"),
                name="uniq_document_content_per_run_page",
            ),
        ),
    ]
