# Generated by Django 5.0 on 2026-04-29 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0036_add_document_content"),
        ("models", "0021_add_discovered_grid"),
        ("projects", "0005_add_project_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_location",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{page, paragraph, char_start, char_end, bbox?}",
                    ),
                ),
                (
                    "statement",
                    models.TextField(
                        help_text="Verbatim normative text as it appears in the document"
                    ),
                ),
                (
                    "normalized",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parsed structured form: {predicate, subject, value, units, lang}",
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("rule", "Rule (normative requirement)"),
                            ("spec", "Specification (concrete value)"),
                            ("requirement", "Requirement (general)"),
                            ("constraint", "Constraint (limit / threshold)"),
                            ("fact", "Fact (descriptive, non-normative)"),
                        ],
                        db_index=True,
                        default="rule",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="0..1 extractor confidence — heuristics ~0.85+, LLM calibrated",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unresolved", "Unresolved (in inbox)"),
                            ("promoted", "Promoted to ProjectConfig"),
                            ("rejected", "Rejected (deliberately ignored)"),
                            ("superseded", "Superseded by a later claim"),
                        ],
                        db_index=True,
                        default="unresolved",
                        max_length=20,
                    ),
                ),
                (
                    "config_section",
                    models.CharField(
                        blank=True,
                        help_text="Which top-level config key was written (default 'claim_derived_rules')",
                        max_length=100,
                    ),
                ),
                (
                    "config_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The exact rule dict written into ProjectConfig.config",
                    ),
                ),
                ("rejected_reason", models.TextField(blank=True)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parsed body the claim was extracted from. Null for IFC-derived claims (future).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="entities.documentcontent",
                    ),
                ),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="models.extractionrun",
                    ),
                ),
                (
                    "promoted_to_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which ProjectConfig the promotion wrote into",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_from_claims",
                        to="projects.projectconfig",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="projects.projectscope",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="models.sourcefile",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes_set",
                        to="entities.claim",
                    ),
                ),
            ],
            options={
                "db_table": "claims",
                "ordering": ["-extracted_at"],
                "indexes": [
                    models.Index(
                        fields=["source_file"], name="claims_source__eb6de4_idx"
                    ),
                    models.Index(fields=["document"], name="claims_documen_3392d4_idx"),
                    models.Index(
                        fields=["status", "claim_type"], name="claims_status_53befe_idx"
                    ),
                    models.Index(fields=["scope"], name="claims_scope_i_901b82_idx"),
                ],
            },
        ),
    ]
