# Generated by Django 5.0 on 2026-05-01 20:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0038_storey_list_claim"),
        ("models", "0021_add_discovered_grid"),
        ("projects", "0007_projectconfig_block_on_storey_deviation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["source_file", "claim_type", "-extracted_at"],
                name="claims_sf_type_extracted_idx",
            ),
        ),
    ]
