# Generated by Django 5.0 on 2026-05-11 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0039_claim_claims_sf_type_extracted_idx"),
        ("models", "0022_add_fragments_format_version"),
        ("projects", "0007_projectconfig_block_on_storey_deviation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("text_block", "Text block (drawing or document body)"),
                            ("layer", "Layer (DWG/DXF/PDF OCG)"),
                            ("annotation", "Annotation (PDF/DWG markup)"),
                            ("title_block_field", "Title-block field (parsed)"),
                            (
                                "sheet_metadata",
                                "Sheet metadata (size, scale, rotation)",
                            ),
                            (
                                "file_metadata",
                                "File-level metadata (author, dates, units)",
                            ),
                            (
                                "extraction_event",
                                "Extraction event (warning, classification)",
                            ),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='Optional dimension within the category — e.g. layer name, title-block field name ("scale", "drawn_by"), metadata key ("author"). Free-form; consumers filter on it.',
                        max_length=128,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        help_text='Primary textual payload. Empty for purely structural observations (e.g. "layer X exists") where the key is the point.',
                    ),
                ),
                (
                    "page_index",
                    models.IntegerField(
                        blank=True,
                        help_text="0-based page index when applicable.",
                        null=True,
                    ),
                ),
                (
                    "bbox",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{x_mm, y_mm, w_mm, h_mm} relative to sheet bottom-left, when applicable.",
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "extraction_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="models.extractionrun",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observations",
                        to="projects.projectscope",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        blank=True,
                        help_text="The drawing sheet this observation belongs to. Null for file-level observations and for document-derived facts.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="entities.drawingsheet",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="models.sourcefile",
                    ),
                ),
            ],
            options={
                "db_table": "observations",
                "ordering": [
                    "source_file_id",
                    "sheet_id",
                    "page_index",
                    "category",
                    "key",
                ],
                "indexes": [
                    models.Index(
                        fields=["source_file", "category"],
                        name="observation_source__e6f122_idx",
                    ),
                    models.Index(
                        fields=["source_file", "sheet", "category"],
                        name="observation_source__5a6f86_idx",
                    ),
                    models.Index(
                        fields=["extraction_run"], name="observation_extract_03f25e_idx"
                    ),
                ],
            },
        ),
    ]
