# Generated by Django 5.0 on 2026-05-11 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0041_backfill_observations"),
        ("models", "0022_add_fragments_format_version"),
        ("projects", "0007_projectconfig_block_on_storey_deviation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="origin_observation",
            field=models.ForeignKey(
                blank=True,
                help_text="The Layer-1 Observation this claim was derived from, when the claim originated from text-block / metadata / annotation matter rather than a parsed document body. Null for document-derived and IFC-derived claims. SET_NULL on observation deletion so the audit trail of an extracted claim survives observation re-emission.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_claims",
                to="entities.observation",
            ),
        ),
        migrations.AddIndex(
            model_name="claim",
            index=models.Index(
                fields=["origin_observation"], name="claims_origin_obs_idx"
            ),
        ),
    ]
