# Generated by Django 5.0 on 2026-05-12 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0042_add_origin_observation_to_claim"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="assigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="claim",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_claims",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ifctype",
            name="entity_ifc_type",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text='IFC class of instances of this type (e.g. "IfcWall" for an IfcWallType). Populated by the FastAPI extractor via IfcRelDefinesByType. Empty when the extractor could not find any related instance.',
                max_length=80,
            ),
        ),
    ]
