# Generated by Django 5.0 on 2026-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entities", "0043_entity_ifc_type_claim_assignee"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisstorey",
            name="guid",
            field=models.CharField(blank=True, db_index=True, max_length=22, null=True),
        ),
    ]
