# Generated by Django 5.0 on 2026-05-10 16:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0007_projectconfig_block_on_storey_deviation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterLibrary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("company", "Company"),
                            ("project", "Project"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "owner_company",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_filter_libraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_libraries",
                        to="projects.project",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_filter_libraries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "filters_filterlibrary",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FilterLibrarySubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_seen_version", models.PositiveIntegerField(default=0)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="filters.filterlibrary",
                    ),
                ),
                (
                    "subscriber_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_library_subscriptions",
                        to="projects.project",
                    ),
                ),
                (
                    "subscriber_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_library_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "filters_filterlibrarysubscription",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("personal", "Personal"),
                            ("company", "Company"),
                            ("project", "Project"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "owner_company",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Company identifier (free-text placeholder until org-model lands). Set when scope=company.",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "payload",
                    models.JSONField(
                        help_text="Serialized FilterContext (frontend ?d= URL state). Schema not validated here."
                    ),
                ),
                (
                    "is_auto_derived",
                    models.BooleanField(
                        default=False,
                        help_text="True for system-derived filters (e.g. EIR/BEP auto-gen). No logic this PR.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when scope=project.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to="projects.project",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set when scope=personal.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "filters_savedfilter",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PinnedFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="filters.savedfilter",
                    ),
                ),
            ],
            options={
                "db_table": "filters_pinnedfilter",
                "ordering": ["user", "position"],
            },
        ),
        migrations.CreateModel(
            name="FilterLibraryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_entries",
                        to="filters.filterlibrary",
                    ),
                ),
                (
                    "saved_filter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_memberships",
                        to="filters.savedfilter",
                    ),
                ),
            ],
            options={
                "db_table": "filters_filterlibraryentry",
                "ordering": ["library", "position"],
            },
        ),
        migrations.AddField(
            model_name="filterlibrary",
            name="entries",
            field=models.ManyToManyField(
                blank=True,
                related_name="libraries",
                through="filters.FilterLibraryEntry",
                to="filters.savedfilter",
            ),
        ),
        migrations.CreateModel(
            name="FilterAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_filter_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="filters.filterlibrary",
                    ),
                ),
                (
                    "saved_filter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="filters.savedfilter",
                    ),
                ),
            ],
            options={
                "db_table": "filters_filterannouncement",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FilterAnnouncementAcknowledgement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="filters.filterannouncement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filter_announcement_acks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "filters_filterannouncementack",
                "ordering": ["-acknowledged_at"],
                "unique_together": {("announcement", "user")},
            },
        ),
        migrations.AddConstraint(
            model_name="filterlibrarysubscription",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("subscriber_user__isnull", False),
                        ("subscriber_project__isnull", True),
                    ),
                    models.Q(
                        ("subscriber_user__isnull", True),
                        ("subscriber_project__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="filterlibrarysubscription_one_subscriber",
            ),
        ),
        migrations.AddConstraint(
            model_name="filterlibrarysubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subscriber_user__isnull", False)),
                fields=("library", "subscriber_user"),
                name="filterlibrarysubscription_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="filterlibrarysubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("subscriber_project__isnull", False)),
                fields=("library", "subscriber_project"),
                name="filterlibrarysubscription_unique_project",
            ),
        ),
        migrations.AddIndex(
            model_name="savedfilter",
            index=models.Index(
                fields=["scope", "owner_user"], name="filters_sav_scope_06c44f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedfilter",
            index=models.Index(
                fields=["scope", "owner_project"], name="filters_sav_scope_457fd5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedfilter",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("scope", "personal"),
                        ("owner_user__isnull", False),
                        ("owner_company__exact", ""),
                        ("owner_project__isnull", True),
                    ),
                    models.Q(
                        ("scope", "company"),
                        ("owner_user__isnull", True),
                        models.Q(("owner_company__exact", ""), _negated=True),
                        ("owner_project__isnull", True),
                    ),
                    models.Q(
                        ("scope", "project"),
                        ("owner_user__isnull", True),
                        ("owner_company__exact", ""),
                        ("owner_project__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="savedfilter_scope_matches_owner",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pinnedfilter",
            unique_together={("user", "saved_filter")},
        ),
        migrations.AlterUniqueTogether(
            name="filterlibraryentry",
            unique_together={("library", "saved_filter")},
        ),
        migrations.AddConstraint(
            model_name="filterlibrary",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("scope", "personal"),
                        ("owner_user__isnull", False),
                        ("owner_company__exact", ""),
                        ("owner_project__isnull", True),
                    ),
                    models.Q(
                        ("scope", "company"),
                        ("owner_user__isnull", True),
                        models.Q(("owner_company__exact", ""), _negated=True),
                        ("owner_project__isnull", True),
                    ),
                    models.Q(
                        ("scope", "project"),
                        ("owner_user__isnull", True),
                        ("owner_company__exact", ""),
                        ("owner_project__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="filterlibrary_scope_matches_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="filterannouncement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("saved_filter__isnull", False), ("library__isnull", True)
                    ),
                    models.Q(
                        ("saved_filter__isnull", True), ("library__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="filterannouncement_one_target",
            ),
        ),
    ]
